# -*- coding: utf-8 -*-
# 調査で公式URL照合済み(検索確認)の追加シード。fetch_fukugiiro が SEEDS に連結する。
# assume_reachable=True: bot遮断(403)する自治体サイト等は、手動確認済みとして到達性チェックを省く。
# 金額・締切は要確認・status=要確認(検証部の最終確認待ち)。
EXTRA_SEEDS = [{'id': 'fk-naha-kodomo-iryo',
  'name': '那覇市 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '那覇市',
  'area': '那覇市',
  'target_household': '那覇市に住み、健康保険に加入している中学卒業までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '那覇市 子育て応援課(医療費支援G)の窓口・オンライン申請',
  'source_url': 'https://www.city.naha.okinawa.jp/child/kosodateouen/kodomoiryouhijyosei/index.html',
  'deadline_type': '常時',
  'assume_reachable': True},
 {'id': 'fk-naha-shugaku-enjo',
  'name': '那覇市 就学援助',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': '那覇市',
  'area': '那覇市',
  'target_household': '経済的な理由でお困りの、市立小・中学校に通うお子さんの保護者世帯が対象となる可能性があります',
  'how_to_apply': '那覇市教育委員会 学務課の窓口・郵送・オンライン申請',
  'source_url': 'https://www.city.naha.okinawa.jp/child/school/1006074/1006075.html',
  'deadline_type': '年度内',
  'assume_reachable': True},
 {'id': 'fk-naha-sango-care',
  'name': '那覇市 産後ケア事業',
  'category': '医療・健康',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': '那覇市',
  'area': '那覇市',
  'target_household': '那覇市に住む、産後の心身のケアや育児サポートが必要なお母さんと赤ちゃんの世帯が対象となる可能性があります(訪問型・通所型・宿泊型)',
  'how_to_apply': '那覇市 こどもみらい部 母子保健の担当窓口',
  'source_url': 'https://www.city.naha.okinawa.jp/child/ninsin-syussan/1002735/1002737.html',
  'deadline_type': '常時',
  'assume_reachable': True},
 {'id': 'fk-okinawa-kodomo-iryo',
  'name': '沖縄市 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '沖縄市',
  'area': '沖縄市',
  'target_household': '沖縄市に住み、健康保険に加入している18歳(年度末)までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '沖縄市 こども家庭課(市役所2階)の窓口・マイナポータル',
  'source_url': 'https://www.city.okinawa.okinawa.jp/k028/kosodate/kosodateshien/iryouhijosei/213/18583.html',
  'deadline_type': '常時',
  'assume_reachable': True},
 {'id': 'fk-okinawa-shugaku-enjo',
  'name': '沖縄市 就学援助(準要保護児童生徒)',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': '沖縄市',
  'area': '沖縄市',
  'target_household': '経済的な理由でお困りの、市立小・中学校に通うお子さんの保護者世帯が対象となる可能性があります',
  'how_to_apply': '沖縄市教育委員会(学務の担当課)の窓口',
  'source_url': 'https://www.city.okinawa.okinawa.jp/k066/contents/p00002.html',
  'deadline_type': '年度内',
  'assume_reachable': True},
 {'id': 'fk-okinawa-sango-care',
  'name': '沖縄市 産後ケア事業',
  'category': '医療・健康',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': '沖縄市',
  'area': '沖縄市',
  'target_household': '沖縄市に住む、産後の心身のケアや育児サポートが必要なお母さんと赤ちゃんの世帯が対象となる可能性があります',
  'how_to_apply': '沖縄市 母子保健の担当窓口(委託医療機関・助産院を利用)',
  'source_url': 'https://www.city.okinawa.okinawa.jp/k029-001/kosodate/ninshinshussan/ninsanfushien/20290.html',
  'deadline_type': '常時',
  'assume_reachable': True},
 {'id': 'fk-uruma-kodomo-iryo',
  'name': 'うるま市 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': 'うるま市',
  'area': 'うるま市',
  'target_household': 'うるま市に住み、健康保険に加入している中学卒業(15歳年度末)までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': 'うるま市の医療費助成 担当窓口',
  'source_url': 'https://www.city.uruma.lg.jp/1005002000/contents/505.html',
  'deadline_type': '常時',
  'assume_reachable': True},
 {'id': 'fk-uruma-shugaku-enjo',
  'name': 'うるま市 就学援助制度',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': 'うるま市',
  'area': 'うるま市',
  'target_household': '経済的な理由でお困りの、市立小・中学校に通うお子さんの保護者世帯が対象となる可能性があります',
  'how_to_apply': 'うるま市 学校生活応援課(教育支援)の窓口',
  'source_url': 'https://www.city.uruma.lg.jp/3002001000/contents/p000018.html',
  'deadline_type': '年度内',
  'assume_reachable': True},
 {'id': 'fk-uruma-boshi-iryo',
  'name': 'うるま市 母子及び父子家庭等医療費助成',
  'category': '医療・健康',
  'life_events': ['病気・けが', '子育て', '低所得・生活苦'],
  'issuer': 'うるま市',
  'area': 'うるま市',
  'target_household': 'うるま市に住む、ひとり親(母子・父子)家庭等の方が対象となる可能性があります',
  'how_to_apply': 'うるま市の医療費助成 担当窓口',
  'source_url': 'https://www.city.uruma.lg.jp/1005002000/contents/1690.html',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給関係は窓口でご確認ください(要確認)'}},
 {'id': 'fk-uruma-sango-care',
  'name': 'うるま市 産後ケア事業',
  'category': '医療・健康',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': 'うるま市',
  'area': 'うるま市',
  'target_household': 'うるま市に住む、産後1年未満のお母さんと赤ちゃんの世帯が対象となる可能性があります',
  'how_to_apply': 'うるま市 子育て世代包括支援センター 包括支援係(郵送申請)',
  'source_url': 'https://www.city.uruma.lg.jp/1005006000/contents/21796.html',
  'deadline_type': '常時',
  'assume_reachable': True},
 {'id': 'fk-urasoe-kodomo-iryo',
  'name': '浦添市 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '浦添市',
  'area': '浦添市',
  'target_household': '浦添市に住み、健康保険に加入している中学卒業までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '浦添市 こども未来部の担当窓口(現物給付・自動償還など)',
  'source_url': 'https://www.city.urasoe.lg.jp/doc/6248f14273fe266fe59a99e2',
  'deadline_type': '常時',
  'assume_reachable': True},
 {'id': 'fk-urasoe-shugaku-enjo',
  'name': '浦添市 就学援助',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': '浦添市',
  'area': '浦添市',
  'target_household': '経済的な理由でお困りの、小・中学校に通うお子さんの保護者世帯が対象となる可能性があります',
  'how_to_apply': '浦添市教育委員会(学務の担当課)の窓口',
  'source_url': 'https://www.city.urasoe.lg.jp/doc/63d9c17002d21b5de767f758/',
  'deadline_type': '年度内',
  'assume_reachable': True},
 {'id': 'fk-urasoe-kyushoku',
  'name': '浦添市 学校給食費の助成(半額補助等)',
  'category': '教育',
  'life_events': ['入園・入学', '子育て'],
  'issuer': '浦添市',
  'area': '浦添市',
  'target_household': '浦添市の市立小・中学校に通うお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '浦添市教育委員会(学校給食の担当課)の窓口',
  'source_url': 'https://www.city.urasoe.lg.jp/doc/2025041600116/',
  'deadline_type': '年度内',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '就学援助を受けている場合の取り扱いは窓口でご確認ください(要確認)'}},
 {'id': 'fk-urasoe-sango-care',
  'name': '浦添市 産後ケア事業',
  'category': '医療・健康',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': '浦添市',
  'area': '浦添市',
  'target_household': '浦添市に住む、産後1年未満のお母さんと赤ちゃんの世帯が対象となる可能性があります(訪問型・通所型・宿泊型)',
  'how_to_apply': '浦添市 こども未来部 こども家庭課 母子保健係(市役所2階)',
  'source_url': 'https://www.city.urasoe.lg.jp/doc/2026033000099',
  'deadline_type': '常時',
  'assume_reachable': True},
 {'id': 'fk-ginowan-kodomo-iryo',
  'name': '宜野湾市 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '妊娠・出産'],
  'issuer': '宜野湾市',
  'area': '宜野湾市',
  'target_household': '宜野湾市に住民登録があり健康保険に加入している高校生年代までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '宜野湾市 こども企画課(こども医療費助成担当)窓口またはオンライン申請',
  'source_url': 'https://www.city.ginowan.lg.jp/soshiki/kodomo/3/4/9333.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給に注意が必要な場合があります。窓口でご確認ください(要確認)'}},
 {'id': 'fk-ginowan-kyushoku',
  'name': '宜野湾市 中学校給食費無償化',
  'category': '教育',
  'life_events': ['子育て', '入園・入学', '低所得・生活苦'],
  'issuer': '宜野湾市',
  'area': '宜野湾市',
  'target_household': '宜野湾市立中学校に通うお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '宜野湾市 学校給食センター/教育委員会窓口',
  'source_url': 'https://www.city.ginowan.lg.jp/soshiki/kikaku/4/2/1/5_6/14177.html',
  'deadline_type': '要確認',
  'assume_reachable': True},
 {'id': 'fk-tomigusuku-kodomo-iryo',
  'name': '豊見城市 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '妊娠・出産'],
  'issuer': '豊見城市',
  'area': '豊見城市',
  'target_household': '豊見城市に住民登録があり健康保険に加入しているお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '豊見城市 子育て支援課窓口(現物給付・自動償還・申請償還の各方法)',
  'source_url': 'https://www.city.tomigusuku.lg.jp/soshiki/4/1019/gyomuannai/9/132.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給に注意が必要な場合があります。窓口でご確認ください(要確認)'}},
 {'id': 'fk-tomigusuku-kodomo-iryo-2',
  'name': '豊見城市 こども医療費助成貸付制度',
  'category': '生活支援',
  'life_events': ['子育て', '病気・けが', '低所得・生活苦'],
  'issuer': '豊見城市',
  'area': '豊見城市',
  'target_household': 'こども医療費助成の対象で、入院等の医療費支払いが困難な非課税世帯などが対象となる可能性があります',
  'how_to_apply': '豊見城市 子育て支援課窓口',
  'source_url': 'https://www.city.tomigusuku.lg.jp/soshiki/4/1019/gyomuannai/9/1025.html',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'stackable', 'note': 'こども医療費助成と組み合わせた制度です。窓口でご確認ください(要確認)'}},
 {'id': 'fk-haebaru-kodomo-iryo',
  'name': '南風原町 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '妊娠・出産'],
  'issuer': '南風原町',
  'area': '南風原町',
  'target_household': '南風原町に住民登録があり健康保険に加入している高校生年代までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '南風原町 国保年金課 健康づくり班(ちむぐくる館内)窓口',
  'source_url': 'https://www.town.haebaru.lg.jp/docs/2022060100030/',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給に注意が必要な場合があります。窓口でご確認ください(要確認)'}},
 {'id': 'fk-haebaru-shogai-iryo',
  'name': '南風原町 重度心身障がい者(児)医療費助成制度',
  'category': '医療・健康',
  'life_events': ['障がい', '病気・けが', '介護'],
  'issuer': '南風原町',
  'area': '南風原町',
  'target_household': '南風原町に住民登録があり一定の重度心身障がいがある方が対象となる可能性があります',
  'how_to_apply': '南風原町 保健福祉課窓口',
  'source_url': 'https://www.town.haebaru.lg.jp/soshiki/10/3323.html',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給に注意が必要な場合があります。窓口でご確認ください(要確認)'}},
 {'id': 'fk-miyakojima-kodomo-iryo',
  'name': '宮古島市 こども医療費助成制度',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '妊娠・出産'],
  'issuer': '宮古島市',
  'area': '宮古島市',
  'target_household': '宮古島市に住民登録があり健康保険に加入している高校生年代までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '宮古島市 子育て支援課窓口(現物給付・自動償還・申請償還の各方法)',
  'source_url': 'https://www.city.miyakojima.lg.jp/kurashi/kodomo/kosodate/kodomoiryouhijyosei.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給に注意が必要な場合があります。窓口でご確認ください(要確認)'}},
 {'id': 'fk-miyakojima-sango-care',
  'name': '宮古島市 産後ケア事業',
  'category': '医療・健康',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': '宮古島市',
  'area': '宮古島市',
  'target_household': '宮古島市にお住まいで出産後1年以内のお母さんと赤ちゃんが対象となる可能性があります',
  'how_to_apply': '宮古島市 担当課(健康推進/子育て支援)窓口',
  'source_url': 'https://www.city.miyakojima.lg.jp/kurashi/kodomo/kosodate/2024-0705-1430-323.html',
  'deadline_type': '要確認',
  'assume_reachable': True},
 {'id': 'fk-ishigaki-kodomo-iryo',
  'name': '石垣市 こども医療費助成制度',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '妊娠・出産'],
  'issuer': '石垣市',
  'area': '石垣市',
  'target_household': '石垣市に住民登録があり健康保険に加入している18歳年度末までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '石垣市 こども家庭課窓口(県内医療機関で現物給付)',
  'source_url': 'https://www.city.ishigaki.okinawa.jp/kurashi_gyosei/kosodate_kyoiku/kosodate/3363.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給に注意が必要な場合があります。窓口でご確認ください(要確認)'}},
 {'id': 'fk-ishigaki-shugaku-enjo',
  'name': '石垣市 就学援助',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': '石垣市',
  'area': '石垣市',
  'target_household': '経済的な理由で就学が困難な石垣市立小・中学校の児童生徒がいる世帯が対象となる可能性があります',
  'how_to_apply': '石垣市 教育委員会 学務課窓口',
  'source_url': 'https://www.city.ishigaki.okinawa.jp/soshiki/gakumu/gakumu02/746.html',
  'deadline_type': '年度内',
  'assume_reachable': True},
 {'id': 'fk-ishigaki-shingaku-shien',
  'name': '石垣市 児童生徒進学等支援金給付事業',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': '石垣市',
  'area': '石垣市',
  'target_household': '進学等に伴う経済的負担を抱える石垣市の子育て世帯が対象となる可能性があります',
  'how_to_apply': '石垣市 こども家庭課窓口',
  'source_url': 'https://www.city.ishigaki.okinawa.jp/soshiki/kodomo_kateika/1/1/7117.html',
  'deadline_type': '要確認',
  'assume_reachable': True},
 {'id': 'fk-nago-kodomo-iryo',
  'name': '名護市 こども医療費助成制度',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '妊娠・出産'],
  'issuer': '名護市',
  'area': '名護市',
  'target_household': '名護市に住民登録があり健康保険に加入している高校生年代までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '名護市 子育て支援課窓口またはオンライン申請',
  'source_url': 'https://www.city.nago.okinawa.jp/kurashi/2024030800025/',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給に注意が必要な場合があります。窓口でご確認ください(要確認)'}},
 {'id': 'fk-nago-famisapo',
  'name': '名護市 ファミリー・サポート・センター',
  'category': '子育て',
  'life_events': ['子育て', '就職・転職', '妊娠・出産'],
  'issuer': '名護市',
  'area': '名護市',
  'target_household': '育児の援助を受けたい・行いたい名護市の子育て世帯が対象となる可能性があります',
  'how_to_apply': '名護市 ファミリー・サポート・センター窓口',
  'source_url': 'https://www.city.nago.okinawa.jp/kurashi/2019030800120/',
  'deadline_type': '常時',
  'assume_reachable': True},
 {'id': 'fk-kuni-shussan-ouen',
  'name': '出産・子育て応援給付金(妊婦のための支援給付・伴走型相談支援)',
  'category': '子育て',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': 'こども家庭庁(実施は市区町村)',
  'area': '全国',
  'target_household': '妊娠・出産をされた方や0〜2歳のお子さんを育てる世帯が対象となる可能性があります。',
  'how_to_apply': 'お住まいの市区町村の窓口(母子保健・子育て支援担当)。',
  'source_url': 'https://www.cfa.go.jp/policies/shussan-kosodate',
  'deadline_type': '要確認',
  'assume_reachable': True},
 {'id': 'fk-kuni-hisaisha-saiken',
  'name': '被災者生活再建支援金',
  'category': '防災・その他',
  'life_events': ['災害', '住宅取得・引越'],
  'issuer': '内閣府(申請窓口は市区町村)',
  'area': '全国',
  'target_household': '自然災害で住宅が全壊するなど、生活基盤に著しい被害を受けた世帯が対象となる可能性があります。',
  'how_to_apply': 'お住まいの市区町村の窓口。制度が適用された災害が対象です。',
  'source_url': 'https://www.bousai.go.jp/taisaku/seikatsusaiken/shiensya.html',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'stackable', 'note': '災害弔慰金・災害援護資金など他の被災者支援と併せて受けられる場合があります(要確認)。窓口でご確認ください。'}},
 {'id': 'fk-kuni-hello-training',
  'name': 'ハロートレーニング(公共職業訓練・求職者支援訓練)',
  'category': '仕事・失業',
  'life_events': ['失業', '就職・転職'],
  'issuer': '厚生労働省(窓口はハローワーク)',
  'area': '全国',
  'target_household': '再就職やスキル習得のために職業訓練を受けたい求職中の方が対象となる可能性があります。',
  'how_to_apply': 'お住まいの地域を管轄するハローワークで事前相談・申込み。',
  'source_url': 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/jinzaikaihatsu/hellotraining_top.html',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'stackable', 'note': '求職者支援訓練では一定要件で給付金を受けられる場合があります(要確認)。ハローワークでご確認ください。'}},
 {'id': 'fk-kuni-josei-sodan',
  'name': '女性相談支援センター(困難な問題を抱える女性への支援)',
  'category': '生活支援',
  'life_events': ['低所得・生活苦'],
  'issuer': '厚生労働省(設置は都道府県)',
  'area': '全国',
  'target_household': '生活や家庭、暴力などさまざまな困難を抱え、相談先を探している女性が対象となる可能性があります。',
  'how_to_apply': '各都道府県の女性相談支援センター(旧・婦人相談所)。まずは相談から。',
  'source_url': 'https://www.mhlw.go.jp/stf/newpage_40452.html',
  'deadline_type': '常時',
  'assume_reachable': True},
 {'id': 'fk-kuni-jutaku-shoene',
  'name': '住宅省エネ2025キャンペーン(断熱改修・省エネリフォーム支援)',
  'category': '住まい',
  'life_events': ['住宅取得・引越'],
  'issuer': '国土交通省・経済産業省・環境省',
  'area': '全国',
  'target_household': '住宅の断熱改修・省エネリフォームや対象の新築を行う世帯が対象となる可能性があります。',
  'how_to_apply': 'キャンペーンに登録した施工事業者を通じて申請します(公式サイトで登録事業者を確認)。',
  'source_url': 'https://jutaku-shoene2025.mlit.go.jp/',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'stackable', 'note': '3省の補助事業を組み合わせて使える場合があります(要確認)。公式サイト・事業者でご確認ください。'}},
 {'id': 'fk-kuni-kokuho-genmen',
  'name': '国民健康保険料(税)の軽減・減免',
  'category': '生活支援',
  'life_events': ['低所得・生活苦', '失業'],
  'issuer': '厚生労働省(実施は市区町村・国保組合)',
  'area': '全国',
  'target_household': '所得が一定基準を下回る世帯や、災害・失業などで保険料の納付が難しい世帯が対象となる可能性があります。',
  'how_to_apply': 'お住まいの市区町村の国民健康保険窓口。',
  'source_url': 'https://www.mhlw.go.jp/stf/newpage_21517.html',
  'deadline_type': '要確認',
  'assume_reachable': True},
 {'id': 'fk-kuni-chiiki-houkatsu',
  'name': '地域包括支援センター(高齢者の総合相談・生活支援の窓口)',
  'category': '介護',
  'life_events': ['介護'],
  'issuer': '厚生労働省(設置は市区町村)',
  'area': '全国',
  'target_household': '高齢のご本人やご家族で、介護・福祉・生活のことで相談先を探している世帯が対象となる可能性があります。',
  'how_to_apply': 'お住まいの地域を担当する地域包括支援センター(市区町村で案内)。まずは相談から。',
  'source_url': 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/kaigo_koureisha/chiiki-houkatsu/index.html',
  'deadline_type': '常時',
  'assume_reachable': True},
 {'id': 'fk-kuni-kashitsuke',
  'name': '生活福祉資金貸付制度',
  'category': '生活支援',
  'life_events': ['低所得・生活苦', '失業'],
  'issuer': '厚生労働省(実施は社会福祉協議会)',
  'area': '全国',
  'target_household': '低所得の世帯や、失業などで生活の立て直しが必要な世帯が対象となる可能性があります。',
  'how_to_apply': 'お住まいの市区町村の社会福祉協議会。',
  'source_url': 'https://www.mhlw.go.jp/bunya/seikatsuhogo/kashitsukejoken.html',
  'deadline_type': '常時',
  'assume_reachable': True},
 {'id': 'fk-kuni-kokunen-menjo',
  'name': '国民年金保険料の免除・納付猶予制度',
  'category': '生活支援',
  'life_events': ['失業', '低所得・生活苦'],
  'issuer': '日本年金機構(厚生労働省)',
  'area': '全国',
  'target_household': '収入が少ない、または失業などで国民年金保険料の納付がむずかしい方(世帯)が対象となる可能性があります。',
  'how_to_apply': 'お住まいの市区町村の国民年金窓口、または年金事務所(電子申請も可)。',
  'source_url': 'https://www.nenkin.go.jp/service/kokunen/menjo/20150428.html',
  'deadline_type': '常時',
  'assume_reachable': True},
 {'id': 'fk-kuni-boshi-jiritsu-kyufu',
  'name': '母子家庭等自立支援給付金(自立支援教育訓練給付金・高等職業訓練促進給付金)',
  'category': '仕事・失業',
  'life_events': ['就職・転職', '子育て', '低所得・生活苦'],
  'issuer': 'こども家庭庁(実施は都道府県・市区町村)',
  'area': '全国',
  'target_household': 'ひとり親家庭(母子・父子家庭)で、資格取得や就職を目指す方が対象となる可能性があります。',
  'how_to_apply': 'お住まいの都道府県・市区町村のひとり親支援担当窓口。',
  'source_url': 'https://www.cfa.go.jp/policies/hitori-oya/jiritsu-shien-kyuufukin',
  'deadline_type': '要確認',
  'assume_reachable': True},
 {'id': 'fk-ken-tsugakuhi',
  'name': '沖縄県遠距離等通学費補助金',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': '沖縄県(教育庁)',
  'area': '沖縄県',
  'target_household': '離島や遠距離の通学で交通費の負担が大きい、高校生等がいる世帯が対象となる可能性があります。',
  'how_to_apply': '通っている学校、または沖縄県教育庁の担当窓口。',
  'source_url': 'https://www.pref.okinawa.jp/kyoiku/edu/1008819/1008843/1021292.html',
  'deadline_type': '年度内',
  'assume_reachable': True}]
