# -*- coding: utf-8 -*-
# 調査で公式URL照合済み(検索確認)の追加シード。fetch_fukugiiro が SEEDS に連結する。
# assume_reachable=True: bot遮断(403)する自治体サイト等は、手動確認済みとして到達性チェックを省く。
# 金額・締切は要確認・status=要確認(検証部の最終確認待ち)。verified=True は公式ページ照合で検証済みに昇格した制度。
EXTRA_SEEDS = [{'id': 'fk-naha-kodomo-iryo',
  'name': '那覇市 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '那覇市',
  'area': '那覇市',
  'target_household': '那覇市に住み、健康保険に加入している中学卒業までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '那覇市 子育て応援課(医療費支援G)の窓口・オンライン申請',
  'source_url': 'https://www.city.naha.okinawa.jp/child/kosodateouen/kodomoiryouhijyosei/index.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '未就学児は通院・入院、小中学生は入院の医療費(保険診療分)を助成。未就学児は窓口無料(現物給付)です(食事療養費等は対象外。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-naha-shugaku-enjo',
  'name': '那覇市 就学援助',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': '那覇市',
  'area': '那覇市',
  'target_household': '経済的な理由でお困りの、市立小・中学校に通うお子さんの保護者世帯が対象となる可能性があります',
  'how_to_apply': '那覇市教育委員会 学務課の窓口・郵送・オンライン申請',
  'source_url': 'https://www.city.naha.okinawa.jp/child/school/1006074/1006075.html',
  'deadline_type': '年度内',
  'amount_note': '給食費・学用品費・修学旅行費などの一部が援助される場合があります(金額は品目・学年で異なります。要確認)',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-naha-sango-care',
  'name': '那覇市 産後ケア事業',
  'category': '医療・健康',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': '那覇市',
  'area': '那覇市',
  'target_household': '那覇市に住む、産後の心身のケアや育児サポートが必要なお母さんと赤ちゃんの世帯が対象となる可能性があります(訪問型・通所型・宿泊型)',
  'how_to_apply': '那覇市 こどもみらい部 母子保健の担当窓口',
  'source_url': 'https://www.city.naha.okinawa.jp/child/ninsin-syussan/1002735/1002737.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-okinawa-kodomo-iryo',
  'name': '沖縄市 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '沖縄市',
  'area': '沖縄市',
  'target_household': '沖縄市に住み健康保険に加入している18歳(年度末)までのお子さんがいる世帯が対象となる可能性があります(令和7年4月〜拡大・所得制限なし)',
  'how_to_apply': '沖縄市 こども家庭課(市役所2階)の窓口・マイナポータル',
  'source_url': 'https://www.city.okinawa.okinawa.jp/k028/kosodate/kosodateshien/iryouhijosei/213/18583.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '18歳(18歳に達した日以後最初の3月31日)までの通院・入院の医療費(保険診療分)を助成。所得制限はありません(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-okinawa-shugaku-enjo',
  'name': '沖縄市 就学援助(準要保護児童生徒)',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': '沖縄市',
  'area': '沖縄市',
  'target_household': '経済的な理由でお困りの、市立小・中学校に通うお子さんの保護者世帯が対象となる可能性があります',
  'how_to_apply': '沖縄市教育委員会(学務の担当課)の窓口',
  'source_url': 'https://www.city.okinawa.okinawa.jp/k066/contents/p00002.html',
  'deadline_type': '年度内',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-okinawa-sango-care',
  'name': '沖縄市 産後ケア事業',
  'category': '医療・健康',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': '沖縄市',
  'area': '沖縄市',
  'target_household': '沖縄市に住む、産後の心身のケアや育児サポートが必要なお母さんと赤ちゃんの世帯が対象となる可能性があります',
  'how_to_apply': '沖縄市 母子保健の担当窓口(委託医療機関・助産院を利用)',
  'source_url': 'https://www.city.okinawa.okinawa.jp/k029-001/kosodate/ninshinshussan/ninsanfushien/20290.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-uruma-kodomo-iryo',
  'name': 'うるま市 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': 'うるま市',
  'area': 'うるま市',
  'target_household': 'うるま市に住み、健康保険に加入している中学卒業(15歳年度末)までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': 'うるま市の医療費助成 担当窓口',
  'source_url': 'https://www.city.uruma.lg.jp/1005002000/contents/505.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '0歳〜中学生(15歳年度末)までの医療費(保険診療分)を助成。令和4年2月から中学卒業まで窓口無料(現物給付)です(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-uruma-shugaku-enjo',
  'name': 'うるま市 就学援助制度',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': 'うるま市',
  'area': 'うるま市',
  'target_household': '経済的な理由でお困りの、市立小・中学校に通うお子さんの保護者世帯が対象となる可能性があります',
  'how_to_apply': 'うるま市 学校生活応援課(教育支援)の窓口',
  'source_url': 'https://www.city.uruma.lg.jp/3002001000/contents/p000018.html',
  'deadline_type': '年度内',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-uruma-boshi-iryo',
  'name': 'うるま市 母子及び父子家庭等医療費助成',
  'category': '医療・健康',
  'life_events': ['病気・けが', '子育て', '低所得・生活苦'],
  'issuer': 'うるま市',
  'area': 'うるま市',
  'target_household': 'うるま市に住む、ひとり親(母子・父子)家庭等の方が対象となる可能性があります',
  'how_to_apply': 'うるま市の医療費助成 担当窓口',
  'source_url': 'https://www.city.uruma.lg.jp/1005002000/contents/1690.html',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給関係は窓口でご確認ください(要確認)'},
  'verified': True,
  'amount_note': 'ひとり親家庭等の通院・入院の医療費(保険診療分)を助成。通院は1医療機関あたり月1,000円の自己負担があります(健診・予防接種等は対象外。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-uruma-sango-care',
  'name': 'うるま市 産後ケア事業',
  'category': '医療・健康',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': 'うるま市',
  'area': 'うるま市',
  'target_household': 'うるま市に住む、産後1年未満のお母さんと赤ちゃんの世帯が対象となる可能性があります',
  'how_to_apply': 'うるま市 子育て世代包括支援センター 包括支援係(郵送申請)',
  'source_url': 'https://www.city.uruma.lg.jp/1005006000/contents/21796.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-urasoe-kodomo-iryo',
  'name': '浦添市 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '浦添市',
  'area': '浦添市',
  'target_household': '浦添市に住み、健康保険に加入している中学卒業までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '浦添市 こども未来部の担当窓口(現物給付・自動償還など)',
  'source_url': 'https://www.city.urasoe.lg.jp/doc/6248f14273fe266fe59a99e2',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': 'こどもの医療費(保険診療分)を助成。平成30年10月から窓口無料(現物給付)に対応。現物給付・自動償還・窓口申請から選べます(対象年齢は要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-urasoe-shugaku-enjo',
  'name': '浦添市 就学援助',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': '浦添市',
  'area': '浦添市',
  'target_household': '経済的な理由でお困りの、小・中学校に通うお子さんの保護者世帯が対象となる可能性があります',
  'how_to_apply': '浦添市教育委員会(学務の担当課)の窓口',
  'source_url': 'https://www.city.urasoe.lg.jp/doc/63d9c17002d21b5de767f758/',
  'deadline_type': '年度内',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-urasoe-kyushoku',
  'name': '浦添市 学校給食費の無償化(令和8年度)',
  'category': '教育',
  'life_events': ['入園・入学', '子育て'],
  'issuer': '浦添市',
  'area': '浦添市',
  'target_household': '浦添市立小・中学校に通うお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '浦添市教育委員会(学校給食の担当課)の窓口',
  'source_url': 'https://www.city.urasoe.lg.jp/doc/2026032600054',
  'deadline_type': '年度内',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '就学援助を受けている場合の取り扱いは窓口でご確認ください(要確認)'},
  'verified': True,
  'amount_note': '令和8年度は市立小中学校の給食費が全額無償化されています(小学生 月額5,700円・中学生 月額6,500円相当。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-urasoe-sango-care',
  'name': '浦添市 産後ケア事業',
  'category': '医療・健康',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': '浦添市',
  'area': '浦添市',
  'target_household': '浦添市に住む、産後1年未満のお母さんと赤ちゃんの世帯が対象となる可能性があります(訪問型・通所型・宿泊型)',
  'how_to_apply': '浦添市 こども未来部 こども家庭課 母子保健係(市役所2階)',
  'source_url': 'https://www.city.urasoe.lg.jp/doc/2026033000099',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-ginowan-kodomo-iryo',
  'name': '宜野湾市 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '妊娠・出産'],
  'issuer': '宜野湾市',
  'area': '宜野湾市',
  'target_household': '宜野湾市に住み健康保険に加入している18歳(高校生年代)までのお子さんがいる世帯が対象となる可能性があります(令和7年10月〜拡大)',
  'how_to_apply': '宜野湾市 こども企画課(こども医療費助成担当)窓口またはオンライン申請',
  'source_url': 'https://www.city.ginowan.lg.jp/soshiki/kodomo/3/4/9333.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給に注意が必要な場合があります。窓口でご確認ください(要確認)'},
  'verified': True,
  'amount_note': '令和7年10月から18歳(高校生年代・年度末)までの通院・入院の医療費(保険診療分)が窓口無料(現物給付)になりました(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-ginowan-kyushoku',
  'name': '宜野湾市 中学校給食費無償化',
  'category': '教育',
  'life_events': ['子育て', '入園・入学', '低所得・生活苦'],
  'issuer': '宜野湾市',
  'area': '宜野湾市',
  'target_household': '宜野湾市立中学校に通うお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '宜野湾市 学校給食センター/教育委員会窓口',
  'source_url': 'https://www.city.ginowan.lg.jp/soshiki/kikaku/4/2/1/5_6/14177.html',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'amount_note': '中学校給食費の無償化に関する制度です。実施状況・対象年度は変わることがあるため、公式サイトで最新をご確認ください(要確認)'},
 {'id': 'fk-tomigusuku-kodomo-iryo',
  'name': '豊見城市 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '妊娠・出産'],
  'issuer': '豊見城市',
  'area': '豊見城市',
  'target_household': '豊見城市に住民登録があり健康保険に加入しているお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '豊見城市 子育て支援課窓口(現物給付・自動償還・申請償還の各方法)',
  'source_url': 'https://www.city.tomigusuku.lg.jp/soshiki/4/1019/gyomuannai/9/132.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給に注意が必要な場合があります。窓口でご確認ください(要確認)'},
  'verified': True,
  'amount_note': 'こどもの医療費(保険診療分)を助成。窓口無料(現物給付)に対応しています(対象年齢は要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-tomigusuku-kodomo-iryo-2',
  'name': '豊見城市 こども医療費助成貸付制度',
  'category': '生活支援',
  'life_events': ['子育て', '病気・けが', '低所得・生活苦'],
  'issuer': '豊見城市',
  'area': '豊見城市',
  'target_household': 'こども医療費助成の対象で、入院等の医療費支払いが困難な非課税世帯などが対象となる可能性があります',
  'how_to_apply': '豊見城市 子育て支援課窓口',
  'source_url': 'https://www.city.tomigusuku.lg.jp/soshiki/4/1019/gyomuannai/9/1025.html',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'stackable', 'note': 'こども医療費助成と組み合わせた制度です。窓口でご確認ください(要確認)'},
  'verified': True,
  'amount_note': 'こども医療費助成の対象で、入院等の医療費の支払いが困難な非課税世帯などに医療資金を貸し付ける制度です(貸付資格認定が必要。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-haebaru-kodomo-iryo',
  'name': '南風原町 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '妊娠・出産'],
  'issuer': '南風原町',
  'area': '南風原町',
  'target_household': '南風原町に住民登録があり健康保険に加入している高校生年代までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '南風原町 国保年金課 健康づくり班(ちむぐくる館内)窓口',
  'source_url': 'https://www.town.haebaru.lg.jp/docs/2022060100030/',
  'deadline_type': '常時',
  'amount_note': '対象年代までの通院・入院の医療費の自己負担分が助成される場合があります(保険適用外は対象外。要確認)',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給に注意が必要な場合があります。窓口でご確認ください(要確認)'},
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-haebaru-shogai-iryo',
  'name': '南風原町 重度心身障がい者(児)医療費助成制度',
  'category': '医療・健康',
  'life_events': ['障がい', '病気・けが', '介護'],
  'issuer': '南風原町',
  'area': '南風原町',
  'target_household': '南風原町に住民登録があり一定の重度心身障がいがある方が対象となる可能性があります',
  'how_to_apply': '南風原町 保健福祉課窓口',
  'source_url': 'https://www.town.haebaru.lg.jp/soshiki/10/3323.html',
  'deadline_type': '要確認',
  'amount_note': '身体障害者手帳1・2級などに該当する方の医療費の自己負担分が助成される場合があります(要確認)',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給に注意が必要な場合があります。窓口でご確認ください(要確認)'},
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-miyakojima-kodomo-iryo',
  'name': '宮古島市 こども医療費助成制度',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '妊娠・出産'],
  'issuer': '宮古島市',
  'area': '宮古島市',
  'target_household': '宮古島市に住み健康保険に加入している18歳(年度末)までのお子さんがいる世帯が対象となる可能性があります(令和8年4月〜高校卒業相当まで拡大)',
  'how_to_apply': '宮古島市 子育て支援課窓口(現物給付・自動償還・申請償還の各方法)',
  'source_url': 'https://www.city.miyakojima.lg.jp/kurashi/kodomo/kosodate/kodomoiryouhijyosei.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給に注意が必要な場合があります。窓口でご確認ください(要確認)'},
  'verified': True,
  'amount_note': '18歳(18歳到達後最初の3月31日)までの医療費(保険診療分)の自己負担分を助成。現物給付等に対応(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-miyakojima-sango-care',
  'name': '宮古島市 産後ケア事業',
  'category': '医療・健康',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': '宮古島市',
  'area': '宮古島市',
  'target_household': '宮古島市にお住まいで出産後1年以内のお母さんと赤ちゃんが対象となる可能性があります',
  'how_to_apply': '宮古島市 担当課(健康推進/子育て支援)窓口',
  'source_url': 'https://www.city.miyakojima.lg.jp/kurashi/kodomo/kosodate/2024-0705-1430-323.html',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '産後1年以内の母子が対象(宿泊・デイ・訪問型)。課税世帯には1回最大2,500円・計5回分の利用料軽減券が交付される場合があります(令和6年4月〜。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-ishigaki-kodomo-iryo',
  'name': '石垣市 こども医療費助成制度',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '妊娠・出産'],
  'issuer': '石垣市',
  'area': '石垣市',
  'target_household': '石垣市に住み健康保険に加入している18歳(年度末)までのお子さんがいる世帯が対象となる可能性があります(令和5年4月〜拡大)',
  'how_to_apply': '石垣市 こども家庭課窓口(県内医療機関で現物給付)',
  'source_url': 'https://www.city.ishigaki.okinawa.jp/kurashi_gyosei/kosodate_kyoiku/kosodate/3363.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給に注意が必要な場合があります。窓口でご確認ください(要確認)'},
  'verified': True,
  'amount_note': '18歳(18歳到達後最初の3月31日)までの外来・入院の医療費(保険診療分)を助成(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-ishigaki-shugaku-enjo',
  'name': '石垣市 就学援助',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': '石垣市',
  'area': '石垣市',
  'target_household': '経済的な理由で就学が困難な石垣市立小・中学校の児童生徒がいる世帯が対象となる可能性があります',
  'how_to_apply': '石垣市 教育委員会 学務課窓口',
  'source_url': 'https://www.city.ishigaki.okinawa.jp/soshiki/gakumu/gakumu02/746.html',
  'deadline_type': '年度内',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-ishigaki-shingaku-shien',
  'name': '石垣市 児童生徒進学等支援金給付事業',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': '石垣市',
  'area': '石垣市',
  'target_household': '進学等に伴う経済的負担を抱える石垣市の子育て世帯が対象となる可能性があります',
  'how_to_apply': '石垣市 こども家庭課窓口',
  'source_url': 'https://www.city.ishigaki.okinawa.jp/soshiki/kodomo_kateika/1/1/7117.html',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'amount_note': '特定の生年のお子さん向けの進学等支援金(ふるさと納税活用)。年度ごとの事業で受付期間が定められています。今年度の実施・受付期間は公式ページで最新をご確認ください(要確認)'},
 {'id': 'fk-nago-kodomo-iryo',
  'name': '名護市 こども医療費助成制度',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '妊娠・出産'],
  'issuer': '名護市',
  'area': '名護市',
  'target_household': '名護市に住民登録があり健康保険に加入している高校生年代までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '名護市 子育て支援課窓口またはオンライン申請',
  'source_url': 'https://www.city.nago.okinawa.jp/kurashi/2024030800025/',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給に注意が必要な場合があります。窓口でご確認ください(要確認)'},
  'verified': True,
  'amount_note': '高校3年生(18歳到達後最初の3月31日)までの医療費(保険診療分)を助成(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-nago-famisapo',
  'name': '名護市 ファミリー・サポート・センター',
  'category': '子育て',
  'life_events': ['子育て', '就職・転職', '妊娠・出産'],
  'issuer': '名護市',
  'area': '名護市',
  'target_household': '育児の援助を受けたい・行いたい名護市の子育て世帯が対象となる可能性があります',
  'how_to_apply': '名護市 ファミリー・サポート・センター窓口',
  'source_url': 'https://www.city.nago.okinawa.jp/kurashi/2019030800120/',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '育児の援助を受けたい人(おねがい会員)と援助したい人(まかせて会員)をつなぐ相互援助の仕組みです。利用料は時間・時間帯で異なります(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kuni-shussan-ouen',
  'name': '出産・子育て応援給付金(妊婦のための支援給付・伴走型相談支援)',
  'category': '子育て',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': 'こども家庭庁(実施は市区町村)',
  'area': '全国',
  'target_household': '妊娠・出産をされた方や0〜2歳のお子さんを育てる世帯が対象となる可能性があります。',
  'how_to_apply': 'お住まいの市区町村の窓口(母子保健・子育て支援担当)。',
  'source_url': 'https://www.cfa.go.jp/policies/shussan-kosodate',
  'deadline_type': '要確認',
  'amount_note': '妊娠届出時と出生届出後にあわせて計10万円相当(妊娠時5万円+出産時5万円)の給付が受けられる場合があります。伴走型の相談支援もあわせて実施されます(自治体で異なります。要確認)',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(こども家庭庁 公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kuni-hisaisha-saiken',
  'name': '被災者生活再建支援金',
  'category': '防災・その他',
  'life_events': ['災害', '住宅取得・引越'],
  'issuer': '内閣府(申請窓口は市区町村)',
  'area': '全国',
  'target_household': '自然災害で住宅が全壊するなど、生活基盤に著しい被害を受けた世帯が対象となる可能性があります。',
  'how_to_apply': 'お住まいの市区町村の窓口。制度が適用された災害が対象です。',
  'source_url': 'https://www.bousai.go.jp/taisaku/seikatsusaiken/shiensya.html',
  'deadline_type': '要確認',
  'amount_note': '基礎支援金(住宅の被害程度に応じ最大100万円)と加算支援金(再建方法に応じ建設・購入で最大200万円/補修100万円/賃借50万円)の合計で、最大300万円が支給される場合があります(世帯人数などで変わります。要確認)',
  'assume_reachable': True,
  'combine': {'type': 'stackable', 'note': '災害弔慰金・災害援護資金など他の被災者支援と併せて受けられる場合があります(要確認)。窓口でご確認ください。'},
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(内閣府 公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kuni-hello-training',
  'name': 'ハロートレーニング(公共職業訓練・求職者支援訓練)',
  'category': '仕事・失業',
  'life_events': ['失業', '就職・転職'],
  'issuer': '厚生労働省(窓口はハローワーク)',
  'area': '全国',
  'target_household': '再就職やスキル習得のために職業訓練を受けたい求職中の方が対象となる可能性があります。',
  'how_to_apply': 'お住まいの地域を管轄するハローワークで事前相談・申込み。',
  'source_url': 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/jinzaikaihatsu/hellotraining_top.html',
  'deadline_type': '要確認',
  'amount_note': '受講料は原則無料です(テキスト代等は自己負担)。求職者支援訓練では一定要件を満たすと月10万円の給付金を受けられる場合があります(要確認)',
  'assume_reachable': True,
  'combine': {'type': 'stackable', 'note': '求職者支援訓練では一定要件で給付金を受けられる場合があります(要確認)。ハローワークでご確認ください。'},
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(厚生労働省 公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kuni-josei-sodan',
  'name': '女性相談支援センター(困難な問題を抱える女性への支援)',
  'category': '生活支援',
  'life_events': ['低所得・生活苦'],
  'issuer': '厚生労働省(設置は都道府県)',
  'area': '全国',
  'target_household': '生活や家庭、暴力などさまざまな困難を抱え、相談先を探している女性が対象となる可能性があります。',
  'how_to_apply': '各都道府県の女性相談支援センター(旧・婦人相談所)。まずは相談から。',
  'source_url': 'https://www.mhlw.go.jp/stf/newpage_40452.html',
  'deadline_type': '常時',
  'amount_note': '相談は無料です。悩みの相談のほか、緊急時の安全確保・一時保護などの支援もあります(全国共通ダイヤル #8778「はなそう なやみ」。要確認)',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(厚生労働省 公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kuni-jutaku-shoene',
  'name': '住宅省エネ2025キャンペーン(断熱改修・省エネリフォーム支援)',
  'category': '住まい',
  'life_events': ['住宅取得・引越'],
  'issuer': '国土交通省・経済産業省・環境省',
  'area': '全国',
  'target_household': '住宅の断熱改修・省エネリフォームや対象の新築を行う世帯が対象となる可能性があります。',
  'how_to_apply': 'キャンペーンに登録した施工事業者を通じて申請します(公式サイトで登録事業者を確認)。',
  'source_url': 'https://jutaku-shoene2025.mlit.go.jp/',
  'deadline_type': '要確認',
  'amount_note': '住宅の断熱改修・省エネリフォーム等への補助です。※先進的窓リノベ2025・給湯省エネ2025など一部事業は2026年3月で受付終了。継続中の対象事業(子育てグリーン住宅支援事業など)は公式サイトで最新をご確認ください(要確認)',
  'assume_reachable': True,
  'combine': {'type': 'stackable', 'note': '3省の補助事業を組み合わせて使える場合があります(要確認)。公式サイト・事業者でご確認ください。'}},
 {'id': 'fk-kuni-kokuho-genmen',
  'name': '国民健康保険料(税)の軽減・減免',
  'category': '生活支援',
  'life_events': ['低所得・生活苦', '失業'],
  'issuer': '厚生労働省(実施は市区町村・国保組合)',
  'area': '全国',
  'target_household': '所得が一定基準を下回る世帯や、災害・失業などで保険料の納付が難しい世帯が対象となる可能性があります。',
  'how_to_apply': 'お住まいの市区町村の国民健康保険窓口。',
  'source_url': 'https://www.mhlw.go.jp/stf/newpage_21517.html',
  'deadline_type': '要確認',
  'amount_note': '所得が基準以下の世帯は保険料の均等割・平等割が7割・5割・2割軽減される場合があります。災害・失業などでは減免・納付猶予を受けられる場合もあります(市区町村でご確認ください。要確認)',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(厚生労働省 公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kuni-chiiki-houkatsu',
  'name': '地域包括支援センター(高齢者の総合相談・生活支援の窓口)',
  'category': '介護',
  'life_events': ['介護'],
  'issuer': '厚生労働省(設置は市区町村)',
  'area': '全国',
  'target_household': '高齢のご本人やご家族で、介護・福祉・生活のことで相談先を探している世帯が対象となる可能性があります。',
  'how_to_apply': 'お住まいの地域を担当する地域包括支援センター(市区町村で案内)。まずは相談から。',
  'source_url': 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/kaigo_koureisha/chiiki-houkatsu/index.html',
  'deadline_type': '常時',
  'amount_note': '相談は無料です。介護・福祉・生活の総合相談に応じ、必要な支援やサービスにつなぐ市区町村の窓口です(要確認)',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(厚生労働省 公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kuni-kashitsuke',
  'name': '生活福祉資金貸付制度',
  'category': '生活支援',
  'life_events': ['低所得・生活苦', '失業'],
  'issuer': '厚生労働省(実施は社会福祉協議会)',
  'area': '全国',
  'target_household': '低所得の世帯や、失業などで生活の立て直しが必要な世帯が対象となる可能性があります。',
  'how_to_apply': 'お住まいの市区町村の社会福祉協議会。',
  'source_url': 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/seikatsuhogo/seikatsu-fukushi-shikin1/kashitsukejoken.html',
  'deadline_type': '常時',
  'amount_note': '低所得・高齢・障がいのある世帯に、資金の貸付と相談支援を行う制度です(貸付の種類・条件は資金ごとに異なります。要確認)',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(厚生労働省 公式ページ照合WebSearch・URL更新)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kuni-kokunen-menjo',
  'name': '国民年金保険料の免除・納付猶予制度',
  'category': '生活支援',
  'life_events': ['失業', '低所得・生活苦'],
  'issuer': '日本年金機構(厚生労働省)',
  'area': '全国',
  'target_household': '収入が少ない、または失業などで国民年金保険料の納付がむずかしい方(世帯)が対象となる可能性があります。',
  'how_to_apply': 'お住まいの市区町村の国民年金窓口、または年金事務所(電子申請も可)。',
  'source_url': 'https://www.nenkin.go.jp/service/kokunen/menjo/20150428.html',
  'deadline_type': '常時',
  'amount_note': '前年所得が一定以下などの場合、保険料の全額または一部が免除・猶予される場合があります。免除期間も年金額に一部反映され、10年以内なら追納も可能です(要確認)',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(日本年金機構 公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kuni-boshi-jiritsu-kyufu',
  'name': '母子家庭等自立支援給付金(自立支援教育訓練給付金・高等職業訓練促進給付金)',
  'category': '仕事・失業',
  'life_events': ['就職・転職', '子育て', '低所得・生活苦'],
  'issuer': 'こども家庭庁(実施は都道府県・市区町村)',
  'area': '全国',
  'target_household': 'ひとり親家庭(母子・父子家庭)で、資格取得や就職を目指す方が対象となる可能性があります。',
  'how_to_apply': 'お住まいの都道府県・市区町村のひとり親支援担当窓口。',
  'source_url': 'https://www.cfa.go.jp/policies/hitori-oya/jiritsu-shien-kyuufukin',
  'deadline_type': '要確認',
  'amount_note': '自立支援教育訓練給付金は受講費用の6割(上限あり)、高等職業訓練促進給付金は資格取得の修業期間中の生活費が支給される場合があります(自治体で異なります。要確認)',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(こども家庭庁 公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-ken-tsugakuhi',
  'name': '沖縄県遠距離等通学費補助金',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': '沖縄県(教育庁)',
  'area': '沖縄県',
  'target_household': '離島や遠距離の通学で交通費の負担が大きい、高校生等がいる世帯が対象となる可能性があります。',
  'how_to_apply': '通っている学校、または沖縄県教育庁の担当窓口。',
  'source_url': 'https://www.pref.okinawa.jp/kyoiku/edu/1008819/1008843/1021292.html',
  'deadline_type': '年度内',
  'amount_note': '所得が一定基準内の世帯で、県内私立高校生等の通学費の一部が補助される場合があります(令和5年度〜。金額・対象は要確認)',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(沖縄県 公式ページ照合WebSearch)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-itoman-kodomo-iryo',
  'name': '糸満市 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '糸満市',
  'area': '糸満市',
  'target_household': '中学校卒業までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '糸満市役所 こども未来課(こども医療費担当)の窓口',
  'source_url': 'https://www.city.itoman.lg.jp/soshiki/16/1019.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成(重度心身障害者医療費など)と重なる場合は調整されることがあります(要確認)/窓口でご確認ください'},
  'verified': True,
  'amount_note': '通院・入院とも中学校卒業(15歳年度末)までの医療費(保険診療分)を助成(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-itoman-shugaku-enjo',
  'name': '糸満市 就学援助制度',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': '糸満市',
  'area': '糸満市',
  'target_household': '経済的にお困りで、生活保護に準じる程度の小・中学生のいる世帯が対象となる可能性があります',
  'how_to_apply': '糸満市教育委員会 学校教育課(市役所5階南側 2番窓口)',
  'source_url': 'https://www.city.itoman.lg.jp/soshiki/32/15477.html',
  'deadline_type': '年度内',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-nanjo-kodomo-iryo',
  'name': '南城市 子ども医療費助成制度',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '南城市',
  'area': '南城市',
  'target_household': '南城市に住み健康保険に加入しているお子さんがいる世帯が対象となる可能性があります(通院は中学3年生まで/入院は18歳年度末まで)',
  'how_to_apply': '南城市役所 子育て支援の担当窓口',
  'source_url': 'https://www.city.nanjo.okinawa.jp/kosodate/kosodate/jyosei/1579339822/',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '令和4年4月から中学卒業まで窓口無料(現物給付)。令和6年4月から入院のみ18歳(年度末)まで拡大されています(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-nanjo-sango-care',
  'name': '南城市 産後ケア事業',
  'category': '医療・健康',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': '南城市',
  'area': '南城市',
  'target_household': '南城市に住民登録があり、産後1年未満で、心身の不調や育児の不安などがあるお母さんと赤ちゃんが対象となる可能性があります',
  'how_to_apply': '南城市 母子健康包括支援センター(子育て世代包括支援)',
  'source_url': 'https://www.city.nanjo.okinawa.jp/kosodate/kosodate/1618553131/',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-yaese-kodomo-iryo',
  'name': '八重瀬町 子ども医療費助成制度',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '八重瀬町',
  'area': '八重瀬町',
  'target_household': '中学生までのお子さんがいる世帯が対象となる可能性があります(2026年4月から対象拡充)',
  'how_to_apply': '八重瀬町役場 児童家庭課の窓口',
  'source_url': 'https://www.town.yaese.lg.jp/docs/2026033100027',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '通院・入院とも医療費(保険診療分)を助成。令和8年度にさらに対象拡充の告知があります。最新の対象年齢は公式ページでご確認ください(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-yaese-kyushoku',
  'name': '八重瀬町 学校給食費の無償化(令和8年度)',
  'category': '教育',
  'life_events': ['入園・入学', '子育て'],
  'issuer': '八重瀬町',
  'area': '八重瀬町',
  'target_household': '八重瀬町立小・中学校に通うお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '八重瀬町 学校・教育の担当窓口(通学先の学校を通じた案内)',
  'source_url': 'https://www.town.yaese.lg.jp/docs/2023121400014/',
  'deadline_type': '年度内',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '就学援助を受けている場合は支援の扱いが異なることがあります(要確認)/窓口でご確認ください'},
  'verified': True,
  'amount_note': '令和8年度から町立小中学校の給食費が完全無償化されています(口座振替手数料も町負担。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-yaese-shugaku-enjo',
  'name': '八重瀬町 就学援助制度',
  'category': '教育',
  'life_events': ['入園・入学', '子育て', '低所得・生活苦'],
  'issuer': '八重瀬町',
  'area': '八重瀬町',
  'target_household': '経済的にお困りで、生活保護に準じる程度の小・中学生のいる世帯が対象となる可能性があります',
  'how_to_apply': '八重瀬町教育委員会(就学援助の担当窓口)',
  'source_url': 'https://www.town.yaese.lg.jp/category/bunya/kurashi/gakko/bunya-shugaku-enjo/',
  'deadline_type': '年度内',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '生活保護に準ずる困窮世帯の小中学生保護者に学用品費等を援助(毎年度申請)。令和8年度は給食費無償化のため給食費の支給はなく、他の費目が対象です(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-nishihara-kodomo-iryo',
  'name': '西原町 こども医療費助成事業',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '西原町',
  'area': '西原町',
  'target_household': '中学校卒業までのお子さんがいる世帯が対象となる可能性があります',
  'how_to_apply': '西原町役場 健康保険課の窓口',
  'source_url': 'https://www.town.nishihara.okinawa.jp/soshiki/9/1776.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '令和4年4月から中学校卒業まで現物給付で助成。令和8年10月から通院・入院とも18歳(高校生年代)まで拡大予定です(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-nishihara-boshi-iryo',
  'name': '西原町 母子父子家庭等医療費助成制度',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '低所得・生活苦'],
  'issuer': '西原町',
  'area': '西原町',
  'target_household': '西原町にお住まいのひとり親家庭(母子・父子家庭等)の方が対象となる可能性があります',
  'how_to_apply': '西原町役場 こども課の窓口',
  'source_url': 'https://www.town.nishihara.okinawa.jp/soshiki/8/1795.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': 'こども医療費助成など他の医療費助成と重なる場合は調整されることがあります(要確認)/窓口でご確認ください'},
  'verified': True,
  'amount_note': 'ひとり親家庭等の医療費(保険診療分)を助成。1医療機関(薬局含む)ごとに月1,000円の自己負担を差し引いた額が対象(平成29年4月から自動償還。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-yonabaru-kodomo-iryo',
  'name': '与那原町 こども医療費助成制度',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '与那原町',
  'area': '与那原町',
  'target_household': '与那原町に住み健康保険に加入している18歳(高校生年代)までのお子さんがいる世帯が対象となる可能性があります(令和6年4月診療分〜拡充)',
  'how_to_apply': '与那原町役場 子育て支援課の窓口',
  'source_url': 'https://www.town.yonabaru.okinawa.jp/soshiki/11/1535.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '18歳(18歳到達後最初の3月31日)までの医療費(保険診療分)を助成(令和6年4月〜。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-yonabaru-sango-care',
  'name': '与那原町 産後ケア事業',
  'category': '医療・健康',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': '与那原町',
  'area': '与那原町',
  'target_household': '与那原町に住所があり、産後1年未満で、家族等の育児協力を得にくい・心身に不調がある等のお母さんと赤ちゃんが対象となる可能性があります',
  'how_to_apply': '与那原町役場 子育て支援課(母子保健の担当窓口)',
  'source_url': 'https://www.town.yonabaru.okinawa.jp/soshiki/12/6941.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-yomitan-kodomo-iryo',
  'name': '読谷村 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '読谷村',
  'area': '読谷村',
  'target_household': '読谷村に住所があり、健康保険に加入している0歳〜中学卒業(15歳到達年度末)までのお子さんがいる世帯が対象となる可能性があります。',
  'how_to_apply': '読谷村役場 こども未来課(母子保健担当)の窓口',
  'source_url': 'https://www.vill.yomitan.okinawa.jp/soshiki/kodomomirai/gyomu/boshi_kenko/support_kenko/642.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'exclusive', 'note': '生活保護や他の医療費助成を受けている場合など対象外となることがあります(要確認/窓口でご確認ください)。'},
  'verified': True,
  'amount_note': '0歳〜中学3年生(15歳年度末)までの医療費(保険診療分)を助成。令和4年4月から入院・通院とも窓口無料(現物給付)(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-yomitan-kyushoku',
  'name': '読谷村 学校給食費の補助(無償化)',
  'category': '教育',
  'life_events': ['子育て', '入園・入学', '低所得・生活苦'],
  'issuer': '読谷村',
  'area': '読谷村',
  'target_household': '読谷村立小中学校に通うお子さんがいる世帯が対象となる可能性があります。',
  'how_to_apply': '読谷村教育委員会(給食センター)の窓口',
  'source_url': 'https://www.vill.yomitan.okinawa.jp/kosodate_kyoiku/school/kyushoku/index.html',
  'deadline_type': '年度内',
  'assume_reachable': True,
  'amount_note': '令和8年度から村立小学校の給食費を無償化。中学校は補助による負担軽減で、無償化の範囲は公式ページで最新をご確認ください(要確認)'},
 {'id': 'fk-yomitan-boshi-iryo',
  'name': '読谷村 母子及び父子家庭等医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '低所得・生活苦'],
  'issuer': '読谷村',
  'area': '読谷村',
  'target_household': '読谷村にお住まいのひとり親家庭(母子・父子家庭)などの方が対象となる可能性があります。',
  'how_to_apply': '読谷村役場 こども未来課(児童福祉担当)の窓口',
  'source_url': 'https://www.vill.yomitan.okinawa.jp/soshiki/kodomomirai/gyomu/jidofukushi/hitorioyashien/1286.html',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給調整がある場合があります(要確認/窓口でご確認ください)。'},
  'verified': True,
  'amount_note': 'ひとり親家庭等の児童(18歳年度末まで)の医療費(保険診療分)を助成。公費医療受給者・第三者行為分は対象外(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-chatan-kodomo-iryo',
  'name': '北谷町 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '北谷町',
  'area': '北谷町',
  'target_household': '北谷町に住み健康保険に加入している18歳(高校生世代)までのお子さんがいる世帯が対象となる可能性があります(令和4年10月〜拡大)',
  'how_to_apply': '北谷町 健康相談センターの窓口',
  'source_url': 'https://www.chatan.jp/kosodate/kosodate/teate_support/kodomoiryogenbutsu.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'exclusive', 'note': '保険適用外の費用などは対象外となることがあります(要確認/窓口でご確認ください)。'},
  'verified': True,
  'amount_note': '0歳〜18歳(年度末)までの医療費(保険診療分)を窓口無料(現物給付)で助成(令和4年10月〜。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-chatan-boshi-iryo',
  'name': '北谷町 母子及び父子家庭等医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '低所得・生活苦'],
  'issuer': '北谷町',
  'area': '北谷町',
  'target_household': '北谷町にお住まいのひとり親家庭(母子・父子家庭)などの方が対象となる可能性があります。',
  'how_to_apply': '北谷町役場の担当窓口(子育て支援担当)',
  'source_url': 'https://www.chatan.jp/kosodate/kosodate/teate_support/boshi_fushi.html',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給調整がある場合があります(要確認/窓口でご確認ください)。'},
  'verified': True,
  'amount_note': 'ひとり親家庭等(児童は18歳年度末まで)の医療費(保険診療分)を助成。1医療機関あたり1人月1,000円の自己負担。健診・予防接種・文書料・差額ベッド等は対象外(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kadena-kodomo-iryo',
  'name': '嘉手納町 子ども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '嘉手納町',
  'area': '嘉手納町',
  'target_household': '嘉手納町に住み健康保険に加入している18歳(年度末)までのお子さんがいる世帯が対象となる可能性があります(令和5年4月〜拡大)',
  'how_to_apply': '嘉手納町役場 子ども家庭課の窓口',
  'source_url': 'https://www.town.kadena.okinawa.jp/life/kur2905.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'exclusive', 'note': '生活保護や他の公費医療助成を受けている場合など対象外となることがあります(要確認/窓口でご確認ください)。'},
  'verified': True,
  'amount_note': '0歳〜18歳(年度末)までの医療費(保険診療分)を助成(令和5年4月〜。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kadena-kyushoku',
  'name': '嘉手納町 学校給食費の無償化',
  'category': '教育',
  'life_events': ['子育て', '入園・入学', '低所得・生活苦'],
  'issuer': '嘉手納町',
  'area': '嘉手納町',
  'target_household': '嘉手納町立の小中学校(保育所・幼稚園を含む)に通うお子さんがいる世帯が対象となる可能性があります。',
  'how_to_apply': '嘉手納町役場(教育委員会・子ども家庭課)の窓口',
  'source_url': 'https://www.town.kadena.okinawa.jp/life/kadena-kosodate-2025.pdf',
  'deadline_type': '年度内',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '幼稚園・こども園から中学校までの給食費を無償化(令和6年度から幼稚園・こども園も対象に追加。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kitanakagusuku-kodomo-iryo',
  'name': '北中城村 子ども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '北中城村',
  'area': '北中城村',
  'target_household': '北中城村に住所があり、各種健康保険に加入している0歳〜中学卒業までのお子さんがいる世帯が対象となる可能性があります。現物給付です。',
  'how_to_apply': '北中城村役場 こども未来課の窓口',
  'source_url': 'https://www.vill.kitanakagusuku.lg.jp/kakuka/kodomo/jidou/teate/3087.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'exclusive', 'note': '生活保護や他の公費医療助成を受けている場合など対象外となることがあります(要確認/窓口でご確認ください)。'},
  'verified': True,
  'amount_note': '0歳〜中学校卒業までの医療費(保険診療分)を助成(令和4年4月〜中学卒業まで拡大。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kitanakagusuku-kyushoku',
  'name': '北中城村 学校給食費補助金交付事業',
  'category': '教育',
  'life_events': ['子育て', '入園・入学', '低所得・生活苦'],
  'issuer': '北中城村',
  'area': '北中城村',
  'target_household': '北中城村立の小中学校に通うお子さんがいる世帯が対象となる可能性があります。',
  'how_to_apply': '北中城村教育委員会(給食調理場)の窓口',
  'source_url': 'https://www.vill.kitanakagusuku.lg.jp/kakuka/iinkai/kyusyoku/1471.html',
  'deadline_type': '年度内',
  'assume_reachable': True,
  'combine': {'type': 'exclusive', 'note': '給食費に未納がある場合は補助の対象外となることがあります(要確認/窓口でご確認ください)。'},
  'verified': True,
  'amount_note': '村立小中学校の給食費を補助する制度です(全額無償化ではなく補助方式)。今年度から保護者の個別申請が不要な代理申請方式に変更。国等の他の公費受給者は対象外(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kitanakagusuku-shugaku-enjo',
  'name': '北中城村 就学援助制度(要保護・準要保護)',
  'category': '教育',
  'life_events': ['子育て', '入園・入学', '低所得・生活苦'],
  'issuer': '北中城村',
  'area': '北中城村',
  'target_household': '経済的な理由で就学が困難と認められる小中学生の保護者(生活保護・非課税・児童扶養手当受給世帯など)が対象となる可能性があります。',
  'how_to_apply': '北中城村教育委員会 教育総務課の窓口',
  'source_url': 'https://www.vill.kitanakagusuku.lg.jp/kakuka/iinkai/kyouiku/teate/274.html',
  'deadline_type': '年度内',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '要保護・準要保護世帯に学用品費等を援助。目安として新入学用品費 小1=54,060円/中1=63,000円、給食費 '
                 '小=月4,200円/中=月4,800円、修学旅行費は実費(小上限22,690円/中上限60,910円)などの記載があります(毎年度申請。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-nakagusuku-kodomo-iryo',
  'name': '中城村 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '中城村',
  'area': '中城村',
  'target_household': '中城村に住み健康保険に加入している18歳(年度末)までのお子さんがいる世帯が対象となる可能性があります(令和5年10月診療分〜拡大)',
  'how_to_apply': '中城村役場 こども課の窓口',
  'source_url': 'https://www.vill.nakagusuku.okinawa.jp/detail.jsp?id=52589&menuid=11411&funcid=2',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '18歳(18歳到達後最初の3月31日)までの入院・通院の医療費(保険診療分)を助成(令和5年10月〜。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-nakagusuku-boshi-iryo',
  'name': '中城村 母子及び父子家庭等医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが', '低所得・生活苦'],
  'issuer': '中城村',
  'area': '中城村',
  'target_household': '中城村にお住まいで健康保険に加入しているひとり親家庭(母子・父子家庭)や養育者家庭などの方が対象となる可能性があります。',
  'how_to_apply': '中城村役場 こども課(医療費助成係)の窓口',
  'source_url': 'https://www.vill.nakagusuku.okinawa.jp/detail.jsp?id=52594&menuid=11411&funcid=2',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の医療費助成との併給調整がある場合があります(要確認/窓口でご確認ください)。'},
  'verified': True,
  'amount_note': '母子・父子・養育家庭の親と児童(0〜18歳年度末)の医療費(保険診療分)を助成(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kunigami-kodomo-iryo',
  'name': '国頭村 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '国頭村',
  'area': '国頭村',
  'target_household': '国頭村に住民登録があり健康保険に加入している0歳から高校卒業年度末までのお子さんがいるご家庭が対象となる可能性があります',
  'how_to_apply': '国頭村役場 福祉課',
  'source_url': 'https://www.vill.kunigami.okinawa.jp/birth/childcare/',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'exclusive', 'note': '生活保護や他の医療費助成を受けている場合は対象外となることがあります(要確認)/窓口でご確認ください'},
  'verified': True,
  'amount_note': '0歳〜高校卒業(18歳到達後最初の3月末)までの通院・入院の医療費(保険診療分)を助成。現物給付/自動償還/償還払いのいずれか(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-higashi-kodomo-iryo',
  'name': '東村 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '東村',
  'area': '東村',
  'target_household': '東村に住民登録があり健康保険に加入しているお子さんがいるご家庭が対象となる可能性があります',
  'how_to_apply': '東村役場(手当・助成の担当窓口)',
  'source_url': 'https://www.vill.higashi.okinawa.jp/kosodate_kyoiku/jidofukushi_hitorioyafukushi/index.html',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'amount_note': '東村のこども医療費助成です。対象年齢・助成範囲は公式ページでご確認ください(要確認)'},
 {'id': 'fk-ogimi-sango-care',
  'name': '大宜味村 産後ケア事業',
  'category': '医療・健康',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': '大宜味村',
  'area': '大宜味村',
  'target_household': '大宜味村に住所があり産後の心身のケアや育児サポートを必要とするお母さんと赤ちゃんが対象となる可能性があります',
  'how_to_apply': '大宜味村役場 住民福祉課',
  'source_url': 'https://www.vill.ogimi.okinawa.jp/kosodate_kyoiku/ninshin_shussan/1042.html',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-ogimi-shugaku-enjo',
  'name': '大宜味村 就学援助',
  'category': '教育',
  'life_events': ['入園・入学', '低所得・生活苦'],
  'issuer': '大宜味村',
  'area': '大宜味村',
  'target_household': '経済的な理由で小・中学校の就学にお困りのご家庭が対象となる可能性があります',
  'how_to_apply': '大宜味村教育委員会',
  'source_url': 'https://www.vill.ogimi.okinawa.jp/docs/2023032200017/',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の給付制度と調整される場合があります(要確認)/窓口でご確認ください'},
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-nakijin-kodomo-iryo',
  'name': '今帰仁村 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '今帰仁村',
  'area': '今帰仁村',
  'target_household': '今帰仁村に住所があり健康保険に加入している中学3年生までのお子さんがいるご家庭が対象となる可能性があります',
  'how_to_apply': '今帰仁村役場 福祉こども課',
  'source_url': 'https://www.nakijin.jp/pagtop/kakuka/hukusikodomoka/2/4_1/2/576.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '中学3年生までの医療費(保険診療分)を助成(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-nakijin-kyushoku',
  'name': '今帰仁村 学校給食費無償化支援',
  'category': '教育',
  'life_events': ['入園・入学', '子育て'],
  'issuer': '今帰仁村',
  'area': '今帰仁村',
  'target_household': '村立小中学校、または今帰仁村在住で村外の小中学校に通うお子さんがいるご家庭が対象となる可能性があります',
  'how_to_apply': '今帰仁村教育委員会',
  'source_url': 'https://www.nakijin.jp/pagtop/kosodate/kyoiku_iinkai/information/5121.html',
  'deadline_type': '年度内',
  'assume_reachable': True,
  'combine': {'type': 'exclusive', 'note': '他制度による支援分は対象外となる場合があります(要確認)/窓口でご確認ください'},
  'verified': True,
  'amount_note': '村立小中学校および村内在住の小中学生の給食費を全額補助(無償化支援)。2026年4月の給食費改定後も継続(過年度の未納がある場合は対象外のことがあります。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-motobu-kodomo-iryo',
  'name': '本部町 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '本部町',
  'area': '本部町',
  'target_household': '本部町に住み健康保険に加入している18歳(高校生年代)までのお子さんがいる世帯が対象となる可能性があります(令和7年4月〜拡大)',
  'how_to_apply': '本部町役場(こども医療費助成の担当窓口)',
  'source_url': 'https://www.town.motobu.okinawa.jp/kosodatekyouiku/kosodatesien/kodomoiryoujyosei',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '令和7年4月から高校生世代(18歳到達後最初の3月31日)まで医療費(保険診療分)を助成。学校でのケガは原則対象外(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-motobu-sango-care',
  'name': '本部町 産後ケア事業',
  'category': '医療・健康',
  'life_events': ['妊娠・出産', '子育て'],
  'issuer': '本部町',
  'area': '本部町',
  'target_household': '本部町に住所があり産後1年以内のお母さんと赤ちゃんが対象となる可能性があります',
  'how_to_apply': '本部町役場(産後ケアの担当窓口)',
  'source_url': 'https://www.town.motobu.okinawa.jp/doc/2026042100018',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '産後1年以内の母子が対象。自己負担の目安は宿泊型4,000円/日帰り(6時間)2,000円/日帰り(3時間)1,000円/訪問型1,000円などの記載があります(非課税・生活保護世帯はキャンセル料免除。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-onna-kodomo-iryo',
  'name': '恩納村 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '恩納村',
  'area': '恩納村',
  'target_household': '恩納村に住所があり健康保険に加入している小学生から高校生のお子さんがいるご家庭が対象となる可能性があります',
  'how_to_apply': '恩納村役場(こども医療費助成の担当窓口)',
  'source_url': 'https://www.vill.onna.okinawa.jp/living/childcare/1648364682/',
  'deadline_type': '常時',
  'assume_reachable': True,
  'combine': {'type': 'exclusive', 'note': '生活保護や交通事故等の第三者行為の場合は対象外となることがあります(要確認)/窓口でご確認ください'},
  'verified': True,
  'amount_note': '高校卒業まで(18歳年度末)の医療費(保険診療分)を助成。生活保護受給者や他制度の助成対象者は対象外の場合があります(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-onna-shugaku-enjo',
  'name': '恩納村 就学援助',
  'category': '教育',
  'life_events': ['入園・入学', '低所得・生活苦'],
  'issuer': '恩納村',
  'area': '恩納村',
  'target_household': '経済的な理由で小・中学校の就学にお困りのご家庭が対象となる可能性があります',
  'how_to_apply': '恩納村教育委員会',
  'source_url': 'https://www.vill.onna.okinawa.jp/living/education/1497599570/1772067691/',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の給付制度と調整される場合があります(要確認)/窓口でご確認ください'},
  'verified': True,
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kumejima-kodomo-iryo',
  'name': '久米島町 こども医療費助成制度',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '久米島町',
  'area': '久米島町',
  'target_household': '久米島町にお住まいで健康保険に加入しているお子さんを育てるご家庭が対象となる可能性があります。',
  'how_to_apply': '久米島町役場の担当課(福祉・こども担当)窓口',
  'source_url': 'https://www.town.kumejima.okinawa.jp/docs/childmedical_expenses/',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '15歳(中学卒業)までの医療費(保険診療分)の自己負担分(調剤・歯科含む)の全部または一部を助成(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kumejima-shussan-josei',
  'name': '久米島町 出産助成金・出産奨励金',
  'category': '子育て',
  'life_events': ['妊娠・出産'],
  'issuer': '久米島町',
  'area': '久米島町',
  'target_household': '島内に分娩できる施設がないため、出産のための渡航・宿泊が必要な久米島町のご家庭が対象となる可能性があります。',
  'how_to_apply': '久米島町役場の担当課窓口',
  'source_url': 'https://www.town.kumejima.okinawa.jp/docs/birth_grant/',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の出産関連の給付と受け取り方が異なる場合があります(要確認)。窓口でご確認ください。'},
  'verified': True,
  'amount_note': '出産奨励金は第1子5万円・第2子10万円・第3子15万円・第4子以降20万円などの記載があります。申請は生後1か月〜1歳の誕生日前日まで(税等の滞納がないこと等が要件。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-taketomi-tokou-iryo',
  'name': '竹富町 こどもの通院にかかる渡航費助成制度',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '竹富町',
  'area': '竹富町',
  'target_household': '島内で受診できず、通院のために船や飛行機での渡航が必要な竹富町のお子さんとご家庭が対象となる可能性があります。',
  'how_to_apply': '竹富町役場(子育て支援担当)窓口。申請書・受診した医療機関の領収書・渡航を証明する領収書などが必要とされています。',
  'source_url': 'https://www.town.taketomi.lg.jp/guide/kosodate/kosodateshien/1632457955/',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': 'こども医療費助成など他の支援と対象範囲が重なる場合があります(要確認)。窓口でご確認ください。'},
  'verified': True,
  'amount_note': 'こども医療費助成の対象受診で本島等へ渡航する際の渡航費(離島割引往復運賃等)を助成。付添の保護者分を含む場合があります(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-taketomi-kodomo-iryo',
  'name': '竹富町 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '竹富町',
  'area': '竹富町',
  'target_household': '竹富町に住所のある0歳から中学3年生までのお子さんを育てるご家庭が対象となる可能性があります。',
  'how_to_apply': '竹富町役場(子育て・健康担当)窓口',
  'source_url': 'https://www.town.taketomi.lg.jp/guide/kosodate/kodomo_kenkou/1531276571/',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '0歳〜中学3年生までの医療費(保険診療分)の自己負担分を助成(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-yonaguni-shogaku',
  'name': '与那国町 貸与型及び給付型奨学金基金',
  'category': '教育',
  'life_events': ['入園・入学'],
  'issuer': '与那国町',
  'area': '与那国町',
  'target_household': '進学にあたり学資の支援が必要な与那国町のご家庭・学生が対象となる可能性があります(貸与型・給付型)。',
  'how_to_apply': '与那国町役場(教育委員会)窓口',
  'source_url': 'https://www.town.yonaguni.okinawa.jp/docs/2026012000010',
  'deadline_type': '要確認',
  'assume_reachable': True,
  'combine': {'type': 'adjust', 'note': '他の奨学金との併用に条件がある場合があります(要確認)。窓口でご確認ください。'},
  'verified': True,
  'amount_note': '大学等に進む町民のお子さん向けの奨学金基金。貸与型は入学時50万円、給付型は在学中の月額5万円などの記載があります(学力・意欲・経済要件あり。要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-ie-kodomo-iryo',
  'name': '伊江村 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '伊江村',
  'area': '伊江村',
  'target_household': '伊江村にお住まいで健康保険に加入しているお子さんを育てるご家庭が対象となる可能性があります。',
  'how_to_apply': '伊江村役場(担当課)窓口',
  'source_url': 'https://www.iejima.org/document/2015021800155/',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '高校卒業までの子どもの医療費(保険診療分)の全部または一部を助成。申請は受診の翌月から1年以内(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-kin-kodomo-iryo',
  'name': '金武町 こども医療費助成制度',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '金武町',
  'area': '金武町',
  'target_household': '金武町にお住まいで健康保険に加入しているお子さんを育てるご家庭が対象となる可能性があります。',
  'how_to_apply': '金武町役場 こども支援課窓口',
  'source_url': 'https://www.town.kin.okinawa.jp/soshiki/kodomoshienka/gyomuannai/keizaitekishien/1412.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '18歳(18歳到達後最初の3月31日。高校等在学中は卒業月まで延長可)の医療費(保険診療分)を助成(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-ginoza-kyushoku',
  'name': '宜野座村 給食費無償化',
  'category': '教育',
  'life_events': ['入園・入学', '子育て'],
  'issuer': '宜野座村',
  'area': '宜野座村',
  'target_household': '村立の幼稚園・小学校・中学校に通う園児・児童・生徒のご家庭が対象となる可能性があります。',
  'how_to_apply': '宜野座村教育委員会窓口',
  'source_url': 'https://www.vill.ginoza.okinawa.jp/soshiki/1009/oshirase/1257.html',
  'deadline_type': '年度内',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '村立幼稚園・小・中学校の給食費を無償化(令和4年度〜継続)。保育所(園)は主食費のみ補助で副食費等は保護者負担が残る場合があります(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'},
 {'id': 'fk-ginoza-kodomo-iryo',
  'name': '宜野座村 こども医療費助成',
  'category': '医療・健康',
  'life_events': ['子育て', '病気・けが'],
  'issuer': '宜野座村',
  'area': '宜野座村',
  'target_household': '宜野座村にお住まいで健康保険に加入しているお子さんを育てるご家庭が対象となる可能性があります。',
  'how_to_apply': '宜野座村役場 健康福祉課窓口',
  'source_url': 'https://www.vill.ginoza.okinawa.jp/tetsuzuki/29.html',
  'deadline_type': '常時',
  'assume_reachable': True,
  'verified': True,
  'amount_note': '出生(転入)から18歳(高校卒業年度末)までの医療費(保険診療分)を助成(要確認)',
  'verified_at': '2026-08-06',
  'verified_by': 'kensho(公式ページ照合WebSearch・並列検証)+小柳さん同席確認 2026-08-06'}]
