/* GLOW企業リレーション台帳 管理画面Web AppのHTML/JS組み立て(Phase 18a: 企業一覧・詳細の閲覧)
 * ブラウザ相当のGAS(global.GlowAdminApp)とNode(module.exports)の両方で動くUMD形式。
 * Node側は tests/glow_ma_adminApp.test.mjs で構造面のみ検証される
 * (google.script.run の実際の往復はGAS実行環境が必要なためNodeでは検証できない)。
 *
 * AdminRunner.gs の renderAdminPage_ がこの関数の戻り値を HtmlService.createHtmlOutput
 * に渡してWeb Appのページとして表示する。基本は読み取り専用だが、Phase 18bで
 * 「関係メモ」欄の更新だけ書き込み経路(updateCompanyMemo)を1つ追加した。
 * それ以外のデータを変更する google.script.run 呼び出しは含まない。
 */
(function (global) {
  "use strict";

  var STYLE = [
    ":root{",
    "/* GLOWコーポレートカラー(テーマに関わらず固定。グラデーション装飾専用) */",
    "--brand-navy-deep:#001b33; --brand-navy:#00335c; --brand-navy-2:#004b86;",
    "--brand-kin:#F88800; --brand-kin-2:#ffa733;",
    "--navy:#00335c; --navy-2:#004b86; --navy-deep:#001b33; --navy-ink:#021c30; --kin:#F88800; --kin-2:#ffa733;",
    "--bg:#EEF1F6; --card:#ffffff; --line:rgba(0,51,92,.13); --line-strong:rgba(0,51,92,.26);",
    "--muted:rgba(2,28,48,.60); --muted-2:rgba(2,28,48,.42);",
    "--good:#0a7a3d; --good-bg:rgba(10,122,61,.12);",
    "--warn:#a15c00; --warn-bg:rgba(248,136,0,.16);",
    "--bad:#b3261e; --bad-bg:rgba(179,38,30,.11);",
    "--hot:#c23b8d; --hot-bg:rgba(194,59,141,.12);",
    "--radius:12px; --radius-lg:16px;",
    "--shadow-sm:0 1px 2px rgba(0,27,51,.06), 0 1px 1px rgba(0,27,51,.04);",
    "--shadow-md:0 8px 24px rgba(0,27,51,.09), 0 2px 6px rgba(0,27,51,.06);",
    "--shadow-lg:0 20px 48px rgba(0,27,51,.16), 0 6px 16px rgba(0,27,51,.08);",
    "color-scheme: light;",
    "}",
    "@media (prefers-color-scheme: dark){",
    ":root{",
    "--bg:#050c16; --card:#0f1c2c; --line:rgba(255,255,255,.10); --line-strong:rgba(255,255,255,.20);",
    "--navy:#8fbdef; --navy-2:#5f9bdb; --navy-deep:#000a14; --navy-ink:#eef4fb; --kin:#ffb454; --kin-2:#ffc97a;",
    "--muted:rgba(238,244,251,.64); --muted-2:rgba(238,244,251,.42);",
    "--good:#3fce85; --good-bg:rgba(63,206,133,.14);",
    "--warn:#e3a53a; --warn-bg:rgba(227,165,58,.16);",
    "--bad:#f0716a; --bad-bg:rgba(240,113,106,.14);",
    "--hot:#e879c2; --hot-bg:rgba(232,121,194,.16);",
    "--shadow-sm:0 1px 2px rgba(0,0,0,.4); --shadow-md:0 8px 24px rgba(0,0,0,.45); --shadow-lg:0 20px 48px rgba(0,0,0,.55);",
    "color-scheme: dark;",
    "}",
    "}",
    ":root[data-theme=\"dark\"]{",
    "--bg:#050c16; --card:#0f1c2c; --line:rgba(255,255,255,.10); --line-strong:rgba(255,255,255,.20);",
    "--navy:#8fbdef; --navy-2:#5f9bdb; --navy-deep:#000a14; --navy-ink:#eef4fb; --kin:#ffb454; --kin-2:#ffc97a;",
    "--muted:rgba(238,244,251,.64); --muted-2:rgba(238,244,251,.42);",
    "--good:#3fce85; --good-bg:rgba(63,206,133,.14);",
    "--warn:#e3a53a; --warn-bg:rgba(227,165,58,.16);",
    "--bad:#f0716a; --bad-bg:rgba(240,113,106,.14);",
    "--hot:#e879c2; --hot-bg:rgba(232,121,194,.16);",
    "--shadow-sm:0 1px 2px rgba(0,0,0,.4); --shadow-md:0 8px 24px rgba(0,0,0,.45); --shadow-lg:0 20px 48px rgba(0,0,0,.55);",
    "color-scheme: dark;",
    "}",
    ":root[data-theme=\"light\"]{",
    "--bg:#EEF1F6; --card:#ffffff; --line:rgba(0,51,92,.13); --line-strong:rgba(0,51,92,.26);",
    "--navy:#00335c; --navy-2:#004b86; --navy-deep:#001b33; --navy-ink:#021c30; --kin:#F88800; --kin-2:#ffa733;",
    "--muted:rgba(2,28,48,.60); --muted-2:rgba(2,28,48,.42);",
    "--good:#0a7a3d; --good-bg:rgba(10,122,61,.12);",
    "--warn:#a15c00; --warn-bg:rgba(248,136,0,.16);",
    "--bad:#b3261e; --bad-bg:rgba(179,38,30,.11);",
    "--hot:#c23b8d; --hot-bg:rgba(194,59,141,.12);",
    "--shadow-sm:0 1px 2px rgba(0,27,51,.06), 0 1px 1px rgba(0,27,51,.04);",
    "--shadow-md:0 8px 24px rgba(0,27,51,.09), 0 2px 6px rgba(0,27,51,.06);",
    "--shadow-lg:0 20px 48px rgba(0,27,51,.16), 0 6px 16px rgba(0,27,51,.08);",
    "color-scheme: light;",
    "}",
    "*{box-sizing:border-box;}",
    "html,body{height:100%;}",
    "body{",
    "margin:0; background:var(--bg); color:var(--navy-ink);",
    "font-family:'Noto Sans JP','Hiragino Kaku Gothic ProN','Yu Gothic',Meiryo,sans-serif;",
    "font-size:14.5px; line-height:1.6; -webkit-font-smoothing:antialiased;",
    "}",
    "button{font-family:inherit;}",
    "::selection{background:var(--kin); color:#1a1000;}",
    "/* ---- App shell ---- */",
    ".app{display:flex; flex-direction:column; min-height:100vh;}",
    ".topbar{",
    "display:flex; align-items:center; gap:14px; padding:12px 26px; flex-wrap:wrap;",
    "background:rgba(2,28,48,.97); /* 沖縄企業のミカタ site-head と同じ濃紺トーン */",
    "border-bottom:1px solid rgba(248,136,0,.35);",
    "color:#fff; position:relative; z-index:2;",
    "}",
    ".topbar .brand-link{display:flex; align-items:center; gap:.6rem; text-decoration:none; color:inherit;}",
    ".topbar .topbar-logo{",
    "height:30px; width:auto; display:block;",
    "animation: logoGlow 3.2s ease-in-out infinite;",
    "}",
    "@keyframes logoGlow{",
    "0%, 100% {",
    "filter:",
    "drop-shadow(0 1px 3px rgba(0,0,0,.35))",
    "drop-shadow(0 0 3px rgba(248,136,0,.45))",
    "drop-shadow(0 0 8px rgba(248,136,0,.28));",
    "}",
    "50% {",
    "filter:",
    "drop-shadow(0 1px 3px rgba(0,0,0,.35))",
    "drop-shadow(0 0 8px rgba(255,167,51,.9))",
    "drop-shadow(0 0 20px rgba(255,167,51,.6))",
    "drop-shadow(0 0 34px rgba(248,136,0,.35));",
    "}",
    "}",
    "@media (prefers-reduced-motion: reduce){",
    ".topbar .topbar-logo{ animation:none; filter:drop-shadow(0 1px 3px rgba(0,0,0,.35)) drop-shadow(0 0 6px rgba(248,136,0,.4)); }",
    "}",
    ".topbar .brand{display:flex; flex-direction:column; gap:1px; line-height:1.25;}",
    ".topbar .brand b{",
    "font-family:'Noto Serif JP','Yu Mincho','Hiragino Mincho ProN',serif;",
    "font-size:1.02rem; letter-spacing:.02em; font-weight:700; color:#F7F5F1;",
    "}",
    ".topbar .brand span{font-size:.66rem; opacity:.78; letter-spacing:.07em; text-transform:uppercase; color:rgba(247,245,241,.78);}",
    ".topbar .helpbtn{",
    "border:1px solid rgba(255,255,255,.35); background:rgba(255,255,255,.08); color:#fff;",
    "font:inherit; font-size:.76rem; font-weight:700; padding:7px 15px; border-radius:999px;",
    "cursor:pointer; white-space:nowrap; margin-left:auto; display:flex; align-items:center; gap:5px;",
    "transition:background .15s ease, transform .15s ease;",
    "}",
    ".topbar .helpbtn:hover{background:rgba(255,255,255,.18); transform:translateY(-1px);}",
    ".topbar .demo-badge{",
    "font-size:.68rem; font-weight:800; letter-spacing:.04em;",
    "background:linear-gradient(120deg, rgba(248,136,0,.28), rgba(255,167,51,.22)); color:#ffe3ba;",
    "border:1px solid rgba(248,136,0,.55);",
    "padding:5px 12px; border-radius:999px; white-space:nowrap;",
    "}",
    ".topbar .asof{font-size:.72rem; opacity:.75; white-space:nowrap; font-variant-numeric:tabular-nums;}",
    ".banner{",
    "font-size:.8rem; color:var(--warn); background:var(--warn-bg); border-bottom:1px solid var(--line);",
    "padding:9px 22px; line-height:1.6;",
    "}",
    ".banner code{background:rgba(0,0,0,.06); border-radius:4px; padding:0 .35em;}",
    "/* ---- Usage guide ---- */",
    ".howto{",
    "max-width:1440px; margin:18px auto 0; padding:0 22px;",
    "}",
    ".howto .howto-card{",
    "background:var(--card); border:1px solid var(--line); border-radius:var(--radius-lg);",
    "overflow:hidden; box-shadow:var(--shadow-sm);",
    "}",
    ".howto summary{",
    "list-style:none; cursor:pointer; padding:14px 20px; display:flex; align-items:center; gap:10px;",
    "font-weight:800; font-size:.88rem; color:var(--navy);",
    "}",
    ".howto summary::-webkit-details-marker{display:none;}",
    ".howto summary .ico{",
    "width:24px; height:24px; border-radius:7px; background:var(--kin); color:#1a1000;",
    "display:flex; align-items:center; justify-content:center; font-size:.78rem; font-weight:900; flex:0 0 auto;",
    "}",
    ".howto summary .chev{margin-left:auto; color:var(--muted); font-size:.72rem; transition:transform .15s ease;}",
    ".howto[open] summary .chev{transform:rotate(180deg);}",
    ".howto summary .hint{font-size:.74rem; font-weight:500; color:var(--muted); margin-left:2px;}",
    ".howto-body{",
    "padding:4px 20px 20px; border-top:1px solid var(--line);",
    "display:grid; grid-template-columns:repeat(3,1fr); gap:22px;",
    "}",
    "@media (max-width:900px){ .howto-body{grid-template-columns:1fr;} }",
    ".howto-body h4{",
    "margin:16px 0 8px; font-size:.78rem; color:var(--navy); letter-spacing:.02em;",
    "display:flex; align-items:center; gap:6px;",
    "}",
    ".howto-body ol, .howto-body ul{margin:0; padding-left:1.25em; font-size:.82rem; color:var(--navy-ink);}",
    ".howto-body li{margin-bottom:7px; line-height:1.65;}",
    ".howto-body li b{color:var(--navy);}",
    ".howto-legend{display:flex; flex-direction:column; gap:9px; margin-top:2px;}",
    ".howto-legend .lg-row{display:flex; align-items:center; gap:9px; font-size:.8rem;}",
    ".howto-legend .lg-row .swatch{flex:0 0 auto;}",
    ".body-grid{",
    "flex:1; display:grid; grid-template-columns:1fr 350px; gap:20px;",
    "padding:22px 22px 44px; max-width:1440px; margin:0 auto; width:100%;",
    "}",
    "@media (max-width:980px){ .body-grid{grid-template-columns:1fr;} }",
    "/* ---- KPI row ---- */",
    ".kpi-row{display:grid; grid-template-columns:repeat(6,1fr); gap:14px; grid-column:1 / -1; margin-bottom:6px;}",
    "@media (max-width:1240px){ .kpi-row{grid-template-columns:repeat(3,1fr);} }",
    "@media (max-width:980px){ .kpi-row{grid-template-columns:repeat(2,1fr);} }",
    ".kpi{",
    "position:relative; background:var(--card); border:1px solid var(--line); border-radius:var(--radius-lg);",
    "padding:18px 18px 18px 22px; box-shadow:var(--shadow-sm); overflow:hidden;",
    "transition:box-shadow .18s ease, transform .18s ease;",
    "}",
    ".kpi{cursor:pointer;}",
    ".kpi:hover{box-shadow:var(--shadow-md); transform:translateY(-2px);}",
    ".kpi:focus-visible{outline:3px solid var(--kin); outline-offset:2px;}",
    ".kpi .expand-hint{position:absolute; right:14px; top:14px; font-size:.68rem; color:var(--muted-2); opacity:0; transition:opacity .15s ease;}",
    ".kpi:hover .expand-hint, .kpi:focus-visible .expand-hint{opacity:1;}",
    ".kpi::before{",
    "content:\"\"; position:absolute; left:0; top:0; bottom:0; width:4px;",
    "background:linear-gradient(180deg, var(--navy), var(--navy-2));",
    "}",
    ".kpi .label{font-size:.72rem; color:var(--muted); font-weight:700; letter-spacing:.02em;}",
    ".kpi .value{font-size:1.85rem; font-weight:800; letter-spacing:-.01em;",
    "background:linear-gradient(120deg, var(--navy), var(--navy-2)); -webkit-background-clip:text; background-clip:text; color:transparent;",
    "font-variant-numeric:tabular-nums; margin-top:5px;}",
    ".kpi .value small{font-size:.62rem; font-weight:700; color:var(--muted); margin-left:3px; -webkit-text-fill-color:var(--muted);}",
    ".kpi .sub{font-size:.74rem; color:var(--muted-2); margin-top:5px; line-height:1.5;}",
    ".kpi.alert::before{background:linear-gradient(180deg, var(--bad), #e0453a);}",
    ".kpi.alert .value{background:linear-gradient(120deg, var(--bad), #e0453a); -webkit-background-clip:text; background-clip:text;}",
    ".kpi.hot::before{background:linear-gradient(180deg, var(--hot), #e879c2);}",
    ".kpi.hot .value{background:linear-gradient(120deg, var(--hot), #e879c2); -webkit-background-clip:text; background-clip:text;}",
    ".kpi.stale::before{background:linear-gradient(180deg, var(--warn), #8a6a2f);}",
    ".kpi.stale .value{background:linear-gradient(120deg, var(--warn), #8a6a2f); -webkit-background-clip:text; background-clip:text;}",
    "/* ---- Main panel ---- */",
    ".panel{background:var(--card); border:1px solid var(--line); border-radius:var(--radius-lg); overflow:hidden; box-shadow:var(--shadow-sm);}",
    ".panel-head{padding:18px 20px 14px; border-bottom:1px solid var(--line); display:flex; align-items:center; gap:12px; flex-wrap:wrap;}",
    ".panel-head h2{font-size:1rem; margin:0; color:var(--navy); flex:0 0 auto; font-weight:800; letter-spacing:.01em; position:relative; padding-left:12px;}",
    ".panel-head h2::before{content:\"\"; position:absolute; left:0; top:1px; bottom:1px; width:4px; border-radius:2px; background:linear-gradient(180deg, var(--kin), var(--kin-2));}",
    ".panel-head .count{font-size:.78rem; color:var(--muted); font-variant-numeric:tabular-nums;}",
    ".filters{display:flex; align-items:center; gap:8px; flex-wrap:wrap; margin-left:auto;}",
    ".filters .flabel{font-size:.7rem; color:var(--muted); font-weight:700; margin-right:-2px;}",
    ".filters select, .filters input[type=\"search\"]{",
    "font:inherit; font-size:.78rem; border:1px solid var(--line-strong); border-radius:8px;",
    "background:var(--bg); color:var(--navy-ink); padding:7px 10px; min-height:34px;",
    "}",
    ".filters select:hover, .filters input[type=\"search\"]:hover{border-color:var(--kin);}",
    ".filters input[type=\"search\"]{min-width:170px;}",
    "table{width:100%; border-collapse:collapse; font-size:.84rem;}",
    "thead th{",
    "position:sticky; top:0; background:var(--bg); text-align:left; font-size:.69rem; color:var(--navy);",
    "text-transform:uppercase; letter-spacing:.04em; font-weight:800; padding:11px 12px; border-bottom:1px solid var(--line-strong);",
    "cursor:pointer; white-space:nowrap; user-select:none;",
    "}",
    "thead th:hover{color:var(--kin);}",
    "thead th .arrow{opacity:.35; font-size:.64rem; margin-left:3px;}",
    "thead th.active{color:var(--kin);}",
    "thead th.active .arrow{opacity:1;}",
    "tbody tr{cursor:pointer; border-bottom:1px solid var(--line);}",
    "tbody tr:nth-child(even){background:rgba(0,51,92,.02);}",
    "tbody tr:hover{background:rgba(248,136,0,.09);}",
    "tbody tr.selected{background:var(--warn-bg);}",
    "tbody td{padding:12px; vertical-align:middle;}",
    "td.num{font-variant-numeric:tabular-nums; white-space:nowrap;}",
    ".table-scroll{overflow-x:auto; max-height:66vh; overflow-y:auto;}",
    ".co-name{font-weight:800; color:var(--navy); font-size:.92rem;}",
    ".co-sub{font-size:.74rem; color:var(--muted-2); margin-top:2px;}",
    ".badge-row{display:flex; gap:5px; flex-wrap:wrap;}",
    ".badge{",
    "display:inline-flex; align-items:center; font-size:.68rem; font-weight:700; padding:3px 9px;",
    "border-radius:999px; white-space:nowrap; letter-spacing:.01em;",
    "}",
    ".badge.route-1{background:rgba(0,51,92,.10); color:var(--navy);}",
    ".badge.route-2{background:rgba(0,51,92,.10); color:var(--navy);}",
    ".badge.route-3{background:rgba(0,51,92,.10); color:var(--navy);}",
    ".badge.prod{background:var(--card); border:1px solid var(--line-strong); color:var(--navy-ink);}",
    ".rank{",
    "display:inline-flex; align-items:center; justify-content:center; width:27px; height:27px;",
    "border-radius:8px; font-weight:800; font-size:.82rem; font-variant-numeric:tabular-nums;",
    "}",
    ".rank-A{background:linear-gradient(135deg, var(--kin), var(--kin-2)); color:#241300; box-shadow:0 2px 8px rgba(248,136,0,.4);}",
    ".rank-B{background:rgba(248,136,0,.24); color:var(--warn);}",
    ".rank-C{background:rgba(0,51,92,.12); color:var(--navy);}",
    ".rank-D{background:rgba(0,51,92,.07); color:var(--muted);}",
    ".urgency{display:flex; align-items:center; gap:7px; font-size:.82rem; font-weight:700; color:var(--navy-ink);}",
    ".dot{width:9px; height:9px; border-radius:50%; flex:0 0 auto;}",
    ".dot.overdue{background:var(--bad); box-shadow:0 0 0 3px var(--bad-bg);}",
    ".dot.soon{background:var(--warn); box-shadow:0 0 0 3px var(--warn-bg);}",
    ".dot.ok{background:var(--good); box-shadow:0 0 0 3px var(--good-bg);}",
    ".dot.none{background:var(--muted-2);}",
    ".u-label{font-size:.72rem; color:var(--muted); font-weight:500; margin-top:2px;}",
    ".hot-flag{",
    "display:inline-flex; align-items:center; gap:4px; font-size:.68rem; font-weight:800;",
    "color:var(--hot); background:var(--hot-bg); padding:3px 9px; border-radius:999px;",
    "}",
    "/* ---- Sidebar: today's queue ---- */",
    ".side{display:flex; flex-direction:column; gap:16px;}",
    ".queue-item{",
    "padding:13px 14px; border-radius:11px; border:1px solid var(--line); cursor:pointer; margin-bottom:9px;",
    "background:var(--bg); transition:border-color .12s ease, transform .12s ease;",
    "}",
    ".queue-item:last-child{margin-bottom:0;}",
    ".queue-item:hover{border-color:var(--kin); transform:translateX(2px);}",
    ".queue-item .qtop{display:flex; justify-content:space-between; align-items:center; gap:8px;}",
    ".queue-item .qname{font-weight:800; font-size:.86rem; color:var(--navy);}",
    ".queue-item .qnote{font-size:.76rem; color:var(--muted); margin-top:5px; line-height:1.55;}",
    ".queue-item .qmeta{font-size:.7rem; color:var(--muted-2); margin-top:6px; padding-top:6px; border-top:1px dashed var(--line);}",
    ".panel-body-pad{padding:14px 16px;}",
    ".empty-note{font-size:.8rem; color:var(--muted-2); padding:8px 2px;}",
    ".workload-row{padding:12px 0; border-bottom:1px solid var(--line);}",
    ".workload-row:last-child{border-bottom:none;}",
    ".workload-row .w-top{display:flex; align-items:center; justify-content:space-between; gap:8px;}",
    ".workload-row .w-name{font-weight:800; color:var(--navy); font-size:.86rem;}",
    ".workload-row.overloaded .w-name{color:var(--bad);}",
    ".workload-row .w-flag{font-size:.66rem; font-weight:800; color:var(--bad); background:var(--bad-bg); padding:3px 9px; border-radius:999px; white-space:nowrap;}",
    ".workload-row .w-stats{display:flex; gap:16px; font-size:.76rem; color:var(--muted); margin-top:6px;}",
    ".workload-row .w-stats span{white-space:nowrap;}",
    ".workload-row .w-stats b{color:var(--navy-ink); font-weight:700; font-variant-numeric:tabular-nums; margin-right:2px;}",
    ".legend{display:flex; flex-direction:column; gap:9px; font-size:.76rem; color:var(--navy-ink);}",
    ".legend .row{display:flex; align-items:center; gap:8px; line-height:1.5;}",
    "/* ---- Drawer / KPI modal ---- */",
    ".scrim{position:fixed; inset:0; background:rgba(2,10,20,.42); opacity:0; pointer-events:none; transition:opacity .18s ease; z-index:40;}",
    ".scrim.open{opacity:1; pointer-events:auto;}",
    ".kpi-modal{",
    "position:fixed; top:50%; left:50%; width:min(640px,92vw); max-height:82vh;",
    "transform:translate(-50%,-46%); background:var(--card); border-radius:var(--radius-lg);",
    "box-shadow:var(--shadow-lg); z-index:42; opacity:0; pointer-events:none;",
    "transition:opacity .18s ease, transform .18s ease; display:flex; flex-direction:column; overflow:hidden;",
    "}",
    ".kpi-modal.open{opacity:1; pointer-events:auto; transform:translate(-50%,-50%);}",
    ".kpi-modal .km-head{padding:20px 24px 14px; border-bottom:1px solid var(--line); position:relative; flex:0 0 auto;}",
    ".kpi-modal .km-head::before{content:\"\"; position:absolute; left:0; right:0; top:0; height:3px;",
    "background:linear-gradient(90deg, var(--brand-navy), var(--brand-navy-2) 40%, var(--brand-kin) 100%);}",
    ".kpi-modal .km-head-row{display:flex; justify-content:space-between; align-items:flex-start; gap:10px;}",
    ".kpi-modal .km-head h3{margin:0; font-size:1.08rem; color:var(--navy);}",
    ".kpi-modal .km-sub{font-size:.8rem; color:var(--muted); margin-top:5px; line-height:1.6;}",
    ".kpi-modal .km-body{padding:18px 24px 24px; overflow-y:auto;}",
    "#letterPreviewModal{width:min(460px,92vw); max-height:88vh;}",
    "#letterPreviewModal .km-body{padding:14px 18px 20px;}",
    "#letterPreviewModal iframe{width:100%; height:480px; border:1px solid var(--line); border-radius:10px; display:block;}",
    ".letter-modal-note{font-size:.78rem; color:var(--muted); line-height:1.6; margin:0 0 12px;}",
    ".km-bars{display:flex; flex-direction:column; gap:11px; margin-bottom:18px;}",
    ".km-bar-row{display:flex; align-items:center; gap:12px; font-size:.84rem;}",
    ".km-bar-row .km-bar-label{min-width:34px; flex:0 0 auto; font-weight:800; white-space:nowrap;}",
    ".km-bar-track{flex:1; height:11px; border-radius:6px; background:var(--bg); overflow:hidden;}",
    ".km-bar-fill{display:block; height:100%; border-radius:6px; background:linear-gradient(90deg, var(--kin), var(--kin-2));}",
    ".km-bar-count{width:26px; text-align:right; font-variant-numeric:tabular-nums; color:var(--muted); font-weight:700;}",
    ".km-section-title{font-size:.7rem; font-weight:800; color:var(--muted); letter-spacing:.03em; text-transform:uppercase; margin:0 0 8px;}",
    ".km-row{display:flex; align-items:center; gap:12px; padding:11px 4px; border-bottom:1px solid var(--line); cursor:pointer; border-radius:8px;}",
    ".km-row:hover{background:rgba(248,136,0,.07);}",
    ".km-row:last-child{border-bottom:none;}",
    ".km-row .km-name{font-weight:700; color:var(--navy); flex:1;}",
    ".km-row .km-name small{display:block; font-weight:500; color:var(--muted-2); font-size:.72rem; margin-top:1px;}",
    ".km-row .km-meta{font-size:.76rem; color:var(--muted); text-align:right;}",
    ".km-empty{font-size:.85rem; color:var(--muted-2); padding:10px 2px;}",
    ".drawer{",
    "position:fixed; top:0; right:0; bottom:0; width:min(560px,94vw); background:var(--card);",
    "border-left:1px solid var(--line); z-index:41; transform:translateX(100%); transition:transform .22s ease;",
    "display:flex; flex-direction:column; box-shadow:var(--shadow-lg);",
    "}",
    ".drawer.open{transform:translateX(0);}",
    ".drawer-head{padding:20px 22px 14px; border-bottom:1px solid var(--line); flex:0 0 auto; position:relative;",
    "display:flex; justify-content:space-between; align-items:flex-start;}",
    ".drawer-head::before{content:\"\"; position:absolute; left:0; right:0; top:0; height:3px;",
    "background:linear-gradient(90deg, var(--brand-navy), var(--brand-navy-2) 40%, var(--brand-kin) 100%);}",
    ".drawer-head .row1{display:flex; justify-content:space-between; align-items:flex-start; gap:10px;}",
    ".drawer-head h3{margin:0; font-size:1.08rem; color:var(--navy);}",
    ".drawer-head .co-meta{font-size:.78rem; color:var(--muted); margin-top:4px;}",
    ".close-btn{",
    "border:none; background:var(--bg); color:var(--navy-ink); width:30px; height:30px; border-radius:8px;",
    "cursor:pointer; font-size:1rem; flex:0 0 auto;",
    "}",
    ".share-btn{",
    "border:none; background:var(--good-bg); color:var(--good); font:inherit; font-size:.78rem; font-weight:800;",
    "padding:0 12px; height:30px; border-radius:999px; cursor:pointer; flex:0 0 auto; white-space:nowrap;",
    "display:flex; align-items:center; gap:5px; transition:filter .15s ease;",
    "}",
    ".share-btn:hover{filter:brightness(0.95);}",
    ".row1-actions{display:flex; align-items:center; gap:8px; flex:0 0 auto;}",
    "#shareModal .km-body{padding:16px 24px 22px;}",
    "#shareModal .share-staff{border:1px solid var(--line); border-radius:10px; padding:8px 12px; max-height:150px; overflow-y:auto; margin-bottom:14px;}",
    "#shareModal .share-staff label{display:flex; align-items:center; gap:8px; padding:6px 2px; font-size:.86rem; cursor:pointer;}",
    "#shareModal textarea{width:100%; min-height:64px; padding:9px 11px; border:1px solid var(--line); border-radius:8px; font:inherit; font-size:.86rem; resize:vertical; margin-bottom:14px; background:var(--card); color:var(--navy-ink);}",
    "#shareModal .share-preview{background:var(--bg); border-radius:8px; padding:10px 12px; font-size:.76rem; color:var(--muted); line-height:1.7; white-space:pre-wrap; margin-bottom:14px; max-height:130px; overflow-y:auto;}",
    "#shareModal .share-warn{color:var(--warn); background:var(--warn-bg); border-radius:8px; padding:8px 12px; font-size:.78rem; margin-bottom:14px; font-weight:700;}",
    "#shareModal .btn.share-send{width:100%; justify-content:center;}",
    ".drawer-stats{display:flex; gap:18px; margin-top:14px; flex-wrap:wrap;}",
    ".drawer-stats .st{font-size:.72rem; color:var(--muted);}",
    ".drawer-stats .st b{display:block; font-size:.98rem; color:var(--navy); font-variant-numeric:tabular-nums;}",
    ".tabs{display:flex; gap:2px; padding:0 22px; border-bottom:1px solid var(--line); flex:0 0 auto;}",
    ".tab{",
    "border:none; background:none; padding:11px 4px; font-size:.82rem; color:var(--muted); cursor:pointer;",
    "border-bottom:2px solid transparent; margin-right:18px; font-weight:700;",
    "}",
    ".tab.active{color:var(--navy); border-bottom-color:var(--kin);}",
    ".drawer-content{flex:1; overflow-y:auto; padding:18px 22px 28px;}",
    ".tabpane{display:none;}",
    ".tabpane.active{display:block;}",
    ".kv-grid{display:grid; grid-template-columns:1fr 1fr; gap:10px 18px; font-size:.82rem;}",
    ".kv-grid .k{color:var(--muted); font-size:.7rem; font-weight:700; letter-spacing:.02em; text-transform:uppercase;}",
    ".kv-grid .v{margin-top:2px;}",
    ".kv-grid .full{grid-column:1 / -1;}",
    ".memo-box{",
    "border:1px solid var(--line-strong); border-left:3px solid var(--kin); border-radius:0 10px 10px 0;",
    "background:var(--warn-bg); padding:14px 16px; margin-bottom:20px;",
    "}",
    ".memo-box .m-head{display:flex; align-items:center; justify-content:space-between; gap:10px; margin-bottom:8px;}",
    ".memo-box .m-title{font-size:.72rem; font-weight:800; color:var(--warn); letter-spacing:.02em; text-transform:uppercase;}",
    ".memo-box .m-title small{display:block; font-weight:500; text-transform:none; color:var(--muted); margin-top:2px; letter-spacing:0;}",
    ".memo-box p{margin:0; font-size:.85rem; line-height:1.7; color:var(--navy-ink);}",
    ".memo-box textarea{",
    "width:100%; min-height:80px; font:inherit; font-size:.85rem; padding:10px 12px; border-radius:8px;",
    "border:1px solid var(--line-strong); background:var(--card); color:var(--navy-ink); resize:vertical;",
    "}",
    ".memo-box .m-actions{display:flex; gap:8px; margin-top:8px;}",
    ".btn.small{padding:6px 14px; font-size:.74rem;}",
    ".hist-item{border-left:2px solid var(--line); padding:2px 0 16px 16px; position:relative; margin-left:4px;}",
    ".hist-item::before{content:\"\";position:absolute; left:-5px; top:4px; width:8px; height:8px; border-radius:50%; background:var(--kin);}",
    ".hist-item .h-top{display:flex; gap:8px; align-items:baseline; flex-wrap:wrap;}",
    ".hist-item .h-date{font-size:.7rem; color:var(--muted-2); font-variant-numeric:tabular-nums;}",
    ".hist-item .h-type{font-size:.78rem; font-weight:700; color:var(--navy);}",
    ".hist-item .h-who{font-size:.7rem; color:var(--muted-2);}",
    ".hist-item .h-memo{font-size:.8rem; color:var(--navy-ink); margin-top:3px; line-height:1.6;}",
    ".hist-item .h-next{font-size:.74rem; color:var(--warn); margin-top:3px;}",
    ".hist-item .h-eta{font-size:.72rem; color:var(--muted); margin-top:3px;}",
    ".hist-item .h-eta b{color:var(--navy); font-weight:700;}",
    ".log-form{border:1px solid var(--line); border-radius:12px; padding:14px; margin-top:18px; background:var(--bg);}",
    ".log-form h4{margin:0 0 10px; font-size:.82rem; color:var(--navy);}",
    ".log-form .frow{display:grid; grid-template-columns:1fr 1fr; gap:8px; margin-bottom:8px;}",
    ".log-form label{font-size:.68rem; color:var(--muted); font-weight:700; display:block; margin-bottom:3px;}",
    ".log-form select, .log-form input, .log-form textarea{",
    "width:100%; font:inherit; font-size:.8rem; border:1px solid var(--line-strong); border-radius:8px;",
    "background:var(--card); color:var(--navy-ink); padding:7px 9px;",
    "}",
    ".log-form textarea{min-height:52px; resize:vertical;}",
    ".log-form .full{grid-column:1 / -1;}",
    ".btn{",
    "border:none; border-radius:999px; font:inherit; font-weight:800; font-size:.8rem; padding:10px 20px;",
    "cursor:pointer; background:linear-gradient(120deg, var(--kin), var(--kin-2)); color:#241300;",
    "box-shadow:0 4px 14px rgba(248,136,0,.35); transition:transform .15s ease, box-shadow .15s ease;",
    "}",
    ".btn:hover{transform:translateY(-1px); box-shadow:0 6px 18px rgba(248,136,0,.45);}",
    ".btn.ghost{background:var(--card); color:var(--navy); border:1px solid var(--line-strong); box-shadow:none;}",
    ".btn.ghost:hover{border-color:var(--navy); box-shadow:none;}",
    ".toast{",
    "position:fixed; bottom:22px; left:50%; transform:translateX(-50%) translateY(8px); opacity:0;",
    "background:var(--navy); color:#fff; padding:10px 18px; border-radius:999px; font-size:.82rem;",
    "pointer-events:none; transition:all .18s ease; z-index:60; font-weight:700;",
    "}",
    ".toast.show{opacity:1; transform:translateX(-50%) translateY(0);}",
    "a.reset-link{color:var(--kin); font-size:.76rem; text-decoration:none; font-weight:700;}",
    "a.reset-link:hover{text-decoration:underline;}",
    "/* ---- Restored: Phase 18a/18b-era UI that predates the Task 8 design demo ---- */",
    "/* (view switcher, empty state, field label/value pairs, memo edit controls: */",
    "/* colors ported from the pre-Task-8 rules to the new --navy/--kin design tokens) */",
    "header{background:var(--navy-deep); color:#fff; padding:.9rem 1.25rem;}",
    "header h1{margin:0; font-size:1.05rem; font-weight:600;}",
    "#viewSwitcher{display:flex; gap:0; background:var(--navy-deep);}",
    "#viewSwitcher button{flex:none; padding:.6rem 1.1rem; border:0; background:none;",
    "color:rgba(255,255,255,.7); cursor:pointer; font:inherit; border-bottom:2px solid transparent;}",
    "#viewSwitcher button.active{color:#fff; border-bottom-color:var(--kin); font-weight:600;}",
    ".viewPane{display:none;}",
    ".viewPane.active{display:block;}",
    ".field{margin-bottom:.7rem;}",
    ".field .label{font-size:.7rem; color:var(--muted); font-weight:700; letter-spacing:.02em;",
    "text-transform:uppercase; display:flex; align-items:center; justify-content:space-between; gap:.5rem;}",
    ".field .value{font-size:.85rem; color:var(--navy-ink); white-space:pre-wrap; margin-top:2px;}",
    ".empty{color:var(--muted-2); padding:1.5rem; text-align:center;}",
    ".btn-small{padding:.25rem .6rem; border:1px solid var(--line-strong); border-radius:.3rem;",
    "background:var(--card); color:var(--navy-ink); cursor:pointer; font:inherit; font-size:.76rem;",
    "text-transform:none; letter-spacing:normal;}",
    ".btn-small:disabled{opacity:.5; cursor:default;}",
    ".btn-primary{background:var(--navy); color:#fff; border-color:var(--navy);}",
    "#memoTextarea{width:100%; min-height:6rem; font:inherit; font-size:.92rem; padding:.5rem;",
    "border:1px solid var(--line-strong); border-radius:.35rem; box-sizing:border-box; margin-top:.3rem;",
    "background:var(--card); color:var(--navy-ink);}",
    "#memoEditControls{margin-top:.4rem; display:flex; align-items:center; gap:.5rem;}",
    "#memoStatus{font-size:.78rem; color:var(--muted);}",
    "#memoStatus.error{color:var(--bad);}"
  ].join("");

  var HEADER_AND_FILTERS = [
    "<header><h1>GLOW企業リレーション台帳</h1></header>",
    "<div id=\"viewSwitcher\"><button id=\"viewCompanyBtn\" class=\"active\">企業一覧</button>",
    "<button id=\"viewPartnerBtn\">紹介パートナー開拓状況</button></div>",
    "<div class=\"filters\" id=\"companyFiltersBar\">",
    "<input type=\"search\" id=\"searchInput\" placeholder=\"会社名・代表者名で検索\">",
    "<select id=\"filterRank\"><option value=\"\">ランク(すべて)</option>",
    "<option value=\"A\">A</option><option value=\"B\">B</option>",
    "<option value=\"C\">C</option><option value=\"D\">D</option></select>",
    "<select id=\"filterStage\"><option value=\"\">現在ステージ(すべて)</option></select>",
    "<select id=\"filterOwner\"><option value=\"\">担当者(すべて)</option></select>",
    "<select id=\"filterRoute\"><option value=\"\">流入ルート(すべて)</option></select>",
    "<select id=\"filterProduct\"><option value=\"\">提案商品(すべて)</option></select>",
    "</div>"
  ].join("");

  var KPI_ROW = [
    "<div class=\"kpi-row\" id=\"kpiRow\"></div>"
  ].join("");

  var TABLE = [
    "<div id=\"companyView\" class=\"viewPane active\">",
    "<table><thead><tr>",
    "<th data-sort=\"name\">会社名/代表者</th>",
    "<th data-sort=\"biz\">業種・所在地</th>",
    "<th data-sort=\"route\">流入ルート</th>",
    "<th data-sort=\"stage\">現在ステージ</th>",
    "<th data-sort=\"products\">提案商品</th>",
    "<th data-sort=\"rank\">ランク</th>",
    "<th data-sort=\"next\">次回アクション</th>",
    "</tr></thead>",
    "<tbody id=\"companyTableBody\"></tbody></table>",
    "<div class=\"empty\" id=\"emptyState\" style=\"display:none\">該当する企業が見つかりません</div>",
    "</div>"
  ].join("");

  var PARTNER_VIEW = [
    "<div id=\"partnerView\" class=\"viewPane\">",
    "<table><thead><tr><th>名称</th><th>種別</th><th>関係性ランク</th><th>対応回数</th></tr></thead>",
    "<tbody id=\"partnerTableBody\"></tbody></table>",
    "<div class=\"empty\" id=\"partnerEmptyState\" style=\"display:none\">該当するパートナーが見つかりません</div>",
    "</div>"
  ].join("");

  var SIDE_PANEL = [
    "<div class=\"side\">",
    "<div class=\"panel\"><div class=\"panel-head\"><h2>本日のネクストアクション</h2></div>",
    "<div class=\"panel-body-pad\" id=\"queue\"></div></div>",
    "<div class=\"panel\"><div class=\"panel-head\"><h2>担当者別ワークロード</h2></div>",
    "<div class=\"panel-body-pad\" id=\"workloadList\"></div></div>",
    "</div>"
  ].join("");

  var DRAWER = [
    "<div class=\"scrim\" id=\"overlay\"></div>",
    "<div class=\"drawer\" id=\"drawer\">",
    "<div class=\"drawer-head\" id=\"drawerHeader\"><div><div id=\"drawerCompanyName\" style=\"font-weight:700\"></div>",
    "<div id=\"drawerCompanyId\" style=\"font-size:0.8rem;color:#7a828a\"></div></div>",
    "<div class=\"row1-actions\">",
    "<button class=\"share-btn\" id=\"shareBtn\">🤝 連携</button>",
    "<button class=\"btn-small\" id=\"letterPreviewBtn\">下書きを見る</button>",
    "<button class=\"close-btn\" id=\"drawerClose\">&times;</button>",
    "</div></div>",
    "<div class=\"tabs\"><button class=\"tab active\" id=\"tabOverviewBtn\">概要</button>",
    "<button class=\"tab\" id=\"tabHistoryBtn\">対応履歴</button></div>",
    "<div class=\"drawer-content\" id=\"drawerBody\">",
    "<div id=\"paneOverview\"></div>",
    "<div id=\"paneHistory\" style=\"display:none\"></div>",
    "</div></div>"
  ].join("");

  var KPI_MODAL = [
    "<div class=\"scrim\" id=\"kpiScrim\"></div>",
    "<div class=\"kpi-modal\" id=\"kpiModal\">",
    "<div class=\"km-head\"><div class=\"km-head-row\">",
    "<div><h3 id=\"kmTitle\"></h3><div class=\"km-sub\" id=\"kmSub\"></div></div>",
    "<button class=\"close-btn\" id=\"kpiModalClose\">&times;</button>",
    "</div></div>",
    "<div class=\"km-body\" id=\"kmBody\"></div>",
    "</div>"
  ].join("");

  var SHARE_MODAL = [
    "<div class=\"kpi-modal\" id=\"shareModal\">",
    "<div class=\"km-head\"><div class=\"km-head-row\">",
    "<div><h3 id=\"shareTitle\"></h3></div>",
    "<button class=\"close-btn\" id=\"shareModalClose\">&times;</button>",
    "</div></div>",
    "<div class=\"km-body\">",
    "<div id=\"shareDncWarn\" class=\"share-warn\" style=\"display:none\">この企業は連絡不要(DNC)登録されています。共有内容にご注意ください。</div>",
    "<div id=\"shareStaffList\" class=\"share-staff\"></div>",
    "<textarea id=\"shareNote\" placeholder=\"一言メモ(任意)\"></textarea>",
    "<div class=\"share-preview\" id=\"sharePreview\"></div>",
    "<button class=\"btn share-send\" id=\"shareSendBtn\">連携する</button>",
    "<div id=\"shareStatus\" style=\"margin-top:8px;font-size:0.78rem;\"></div>",
    "</div></div>"
  ].join("");

  var LETTER_PREVIEW_MODAL = [
    "<div class=\"kpi-modal\" id=\"letterPreviewModal\">",
    "<div class=\"km-head\"><div class=\"km-head-row\">",
    "<div><h3>レター下書き</h3></div>",
    "<button class=\"close-btn\" id=\"letterPreviewModalClose\">&times;</button>",
    "</div></div>",
    "<div class=\"km-body\" id=\"letterPreviewBody\"></div>",
    "</div>"
  ].join("");

  var PARTNER_DRAWER = [
    "<div class=\"scrim\" id=\"partnerOverlay\"></div>",
    "<div class=\"drawer\" id=\"partnerDrawer\">",
    "<div class=\"drawer-head\" id=\"partnerDrawerHeader\"><div><div id=\"partnerDrawerName\" style=\"font-weight:700\"></div>",
    "<div id=\"partnerDrawerId\" style=\"font-size:0.8rem;color:#7a828a\"></div></div>",
    "<button class=\"close-btn\" id=\"partnerDrawerClose\">&times;</button></div>",
    "<div class=\"tabs\"><button class=\"tab active\" id=\"tabPartnerOverviewBtn\">概要</button>",
    "<button class=\"tab\" id=\"tabPartnerHistoryBtn\">対応履歴</button>",
    "<button class=\"tab\" id=\"tabPartnerReferralsBtn\">紹介実績</button></div>",
    "<div class=\"drawer-content\" id=\"partnerDrawerBody\">",
    "<div id=\"panePartnerOverview\"></div>",
    "<div id=\"panePartnerHistory\" style=\"display:none\"></div>",
    "<div id=\"panePartnerReferrals\" style=\"display:none\"></div>",
    "</div></div>"
  ].join("");

  var SCRIPT = [
    "var currentFilters = { search: '', rank: '', stage: '', owner: '', route: '', product: '' };",
    "var memoEditing = false;",
    "var memoCompanyId = null;",
    "var memoOriginalValue = '';",
    "function escapeHtml(value){return String(value===undefined||value===null?'':value)",
    ".replace(/&/g,'&amp;').replace(/\"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}",

    "function loadFilterOptions(){",
    "google.script.run.withSuccessHandler(function(options){",
    "var stageSelect = document.getElementById('filterStage');",
    "(options.stages||[]).forEach(function(stage){",
    "var opt = document.createElement('option'); opt.value = stage; opt.textContent = stage;",
    "stageSelect.appendChild(opt);});",
    "var ownerSelect = document.getElementById('filterOwner');",
    "(options.owners||[]).forEach(function(owner){",
    "var opt = document.createElement('option'); opt.value = owner; opt.textContent = owner;",
    "ownerSelect.appendChild(opt);});",
    "var routeSelect = document.getElementById('filterRoute');",
    "(options.routes||[]).forEach(function(route){",
    "var opt = document.createElement('option'); opt.value = route; opt.textContent = route;",
    "routeSelect.appendChild(opt);});",
    "var productSelect = document.getElementById('filterProduct');",
    "(options.products||[]).forEach(function(product){",
    "var opt = document.createElement('option'); opt.value = product; opt.textContent = product;",
    "productSelect.appendChild(opt);});",
    "}).withFailureHandler(function(){}).getFilterOptions();",
    "}",

    "function loadKpiSummary(){",
    "google.script.run.withSuccessHandler(renderKpiRow).withFailureHandler(function(){",
    "document.getElementById('kpiRow').innerHTML = '';",
    "}).getKpiSummary();",
    "}",

    "var LAST_KPI_SUMMARY = null;",
    "function renderKpiRow(summary){",
    "LAST_KPI_SUMMARY = summary;",
    "var byRank = summary.byRank || {A:0,B:0,C:0,D:0};",
    "var kpis = [",
    "{key:'total', label:'パイプライン企業数', value:summary.total, sub:'絞り込みなしの全企業数'},",
    "{key:'overdueOrUntouched', label:'本日の掘り起こし対象', value:summary.overdueOrUntouched, sub:'未着手・対応期限超過', cls:'alert'},",
    "{key:'hot', label:'即時アラート', value:summary.hot, sub:'本日、企業側から反応あり', cls:'hot'},",
    "{key:'rank', label:'ランク内訳', value:'A'+byRank.A+'/B'+byRank.B+'/C'+byRank.C+'/D'+byRank.D, sub:'ランク別企業数'},",
    "{key:'deal', label:'提案中・案件化', value:summary.deal, sub:'商談が進行中の企業数'},",
    "{key:'stale', label:'長期検討企業', value:summary.stale, sub:'標準サイクルの2倍以上、未接触', cls:'stale'}",
    "];",
    "var row = document.getElementById('kpiRow');",
    "row.innerHTML = kpis.map(function(k){",
    "return '<div class=\"kpi ' + (k.cls||'') + '\" data-kpi=\"' + k.key + '\" role=\"button\" tabindex=\"0\">' +",
    "'<div class=\"label\">' + escapeHtml(k.label) + '</div>' +",
    "'<div class=\"value\">' + escapeHtml(k.value) + '</div>' +",
    "'<div class=\"sub\">' + escapeHtml(k.sub) + '</div></div>';",
    "}).join('');",
    "row.querySelectorAll('.kpi').forEach(function(el){",
    "el.addEventListener('click', function(){ openKpiModal(el.dataset.kpi); });",
    "});",
    "}",

    "function openKpiModal(key){",
    "document.getElementById('kmTitle').textContent = key;",
    "document.getElementById('kmSub').textContent = 'クリックした企業の詳細を開けます';",
    "document.getElementById('kmBody').innerHTML = '<p class=\"km-empty\">一覧側の絞り込みで詳細な内訳を確認してください。</p>';",
    "document.getElementById('kpiScrim').classList.add('open');",
    "document.getElementById('kpiModal').classList.add('open');",
    "}",

    "function closeKpiModal(){",
    "document.getElementById('kpiModal').classList.remove('open');",
    "document.getElementById('kpiScrim').classList.remove('open');",
    "}",

    "function loadQueue(){",
    "google.script.run.withSuccessHandler(renderQueue).withFailureHandler(function(){",
    "document.getElementById('queue').innerHTML = '';",
    "}).getNextActionQueue();",
    "}",

    "function renderQueue(items){",
    "var el = document.getElementById('queue');",
    "if (!items || items.length===0){ el.innerHTML = '<p class=\"empty-note\">本日、優先度の高い企業はありません。</p>'; return; }",
    "el.innerHTML = items.map(function(c){",
    "var flag = c['本日反応あり'] ? '<span class=\"hot-flag\">反応あり</span>' : '<span class=\"rank rank-'+escapeHtml(c['ランク'])+'\">'+escapeHtml(c['ランク'])+'</span>';",
    "return '<div class=\"queue-item\" data-id=\"'+escapeHtml(c['企業ID'])+'\">' +",
    "'<div class=\"qtop\"><span class=\"qname\">'+escapeHtml(c['会社名'])+'</span>'+flag+'</div>' +",
    "'<div class=\"qmeta\">'+escapeHtml(c['担当者']||'未割当')+' 担当 ・ 次回アクション予定日: '+escapeHtml(c['次回アクション予定日']||'未設定')+'</div>' +",
    "'</div>';",
    "}).join('');",
    "el.querySelectorAll('.queue-item').forEach(function(item){",
    "item.addEventListener('click', function(){ openDrawer(item.dataset.id); });",
    "});",
    "}",

    "function loadWorkload(){",
    "google.script.run.withSuccessHandler(renderWorkload).withFailureHandler(function(){",
    "document.getElementById('workloadList').innerHTML = '';",
    "}).getOwnerWorkload();",
    "}",

    "function renderWorkload(rows){",
    "var el = document.getElementById('workloadList');",
    "if (!rows || rows.length===0){ el.innerHTML = '<p class=\"empty-note\">担当者が設定された企業がありません。</p>'; return; }",
    "el.innerHTML = rows.map(function(r){",
    "return '<div class=\"workload-row\"><div class=\"w-top\"><span class=\"w-name\">'+escapeHtml(r.owner)+'</span></div>' +",
    "'<div class=\"w-stats\"><span><b>'+r.total+'</b>件担当</span><span><b>'+r.overdueOrUntouched+'</b>件 未着手/期限超過</span></div>' +",
    "'</div>';",
    "}).join('');",
    "}",

    "function loadList(){",
    "google.script.run.withSuccessHandler(renderTable).withFailureHandler(function(error){",
    "document.getElementById('companyTableBody').innerHTML = '';",
    "var empty = document.getElementById('emptyState');",
    "empty.style.display = 'block'; empty.textContent = '読み込みに失敗しました。再読み込みしてください。';",
    "}).getCompanyList(currentFilters);",
    "}",

    "function renderTable(rows){",
    "var tbody = document.getElementById('companyTableBody'); tbody.innerHTML = '';",
    "var empty = document.getElementById('emptyState');",
    "if (!rows || rows.length === 0){ empty.style.display = 'block';",
    "empty.textContent = '該当する企業が見つかりません'; return; }",
    "empty.style.display = 'none';",
    "rows.forEach(function(row){",
    "var tr = document.createElement('tr');",
    "var routeBadges = (row['流入ルート']||[]).map(function(r){ return '<span class=\"badge route-1\">'+escapeHtml(r)+'</span>'; }).join('');",
    "var productBadges = (row['提案商品']||[]).map(function(p){ return '<span class=\"badge prod\">'+escapeHtml(p)+'</span>'; }).join('');",
    "tr.innerHTML = '<td><div class=\"co-name\">' + escapeHtml(row['会社名']) + '</div></td>' +",
    "'<td>' + escapeHtml(row['業種']) + '<div class=\"co-sub\">' + escapeHtml(row['所在地']) + '</div></td>' +",
    "'<td><div class=\"badge-row\">' + routeBadges + '</div></td>' +",
    "'<td>' + escapeHtml(row['現在ステージ']) + '</td>' +",
    "'<td><div class=\"badge-row\">' + productBadges + '</div></td>' +",
    "'<td><span class=\"rank rank-' + escapeHtml(row['ランク']) + '\">' + escapeHtml(row['ランク']) + '</span></td>' +",
    "'<td>' + escapeHtml(row['次回アクション予定日']) + '</td>';",
    "tr.addEventListener('click', function(){ openDrawer(row['企業ID']); });",
    "tbody.appendChild(tr);});",
    "}",

    "function openDrawer(companyId){",
    "if (memoEditing && !confirm('保存されていない変更があります。破棄しますか?')) { return; }",
    "memoEditing = false;",
    "document.getElementById('drawer').classList.add('open');",
    "document.getElementById('overlay').classList.add('open');",
    "document.getElementById('drawerCompanyName').textContent = '読み込み中…';",
    "document.getElementById('drawerCompanyId').textContent = companyId;",
    "google.script.run.withSuccessHandler(renderDrawer).withFailureHandler(function(){",
    "document.getElementById('drawerCompanyName').textContent = '読み込みに失敗しました。再読み込みしてください。';",
    "}).getCompanyDetail(companyId);",
    "}",

    "function renderDrawer(detail){",
    "if (!detail){ document.getElementById('drawerCompanyName').textContent = '該当する企業が見つかりません';",
    "document.getElementById('paneOverview').innerHTML = ''; document.getElementById('paneHistory').innerHTML = ''; return; }",
    "var c = detail.company;",
    "shareTargetDnc = !!c['連絡不要'];",
    "document.getElementById('drawerCompanyName').textContent = c['会社名'] || '(社名未登録)';",
    "document.getElementById('drawerCompanyId').textContent = c['企業ID'];",
    "var fields = [",
    "['業種', c['業種']], ['代表者名', c['代表者名']], ['所在地', c['所在地']],",
    "['電話番号', c['電話番号']], ['窓口担当者名', c['窓口担当者名']], ['携帯番号', c['携帯番号']],",
    "['ランク', c['ランク']], ['初期スコア', c['初期スコア']], ['反応スコア', c['反応スコア']],",
    "['総合スコア', c['総合スコア']], ['現在ステージ', c['現在ステージ']],",
    "['後継者状況', c['後継者状況']]",
    "];",
    "document.getElementById('paneOverview').innerHTML = fields.map(function(f){",
    "return '<div class=\"field\"><div class=\"label\">' + escapeHtml(f[0]) + '</div>' +",
    "'<div class=\"value\">' + (escapeHtml(f[1]) || '—') + '</div></div>';",
    "}).join('') + renderMemoField(c['関係メモ']);",
    "attachMemoHandlers(c['企業ID'], c['関係メモ']);",
    "var history = detail.history || [];",
    "document.getElementById('paneHistory').innerHTML = history.length === 0",
    "? '<div class=\"empty\">対応履歴がありません</div>'",
    ": history.map(function(h){",
    "return '<div class=\"field\"><div class=\"label\">' + escapeHtml(h['日付']) + '・' + escapeHtml(h['種別']) + '</div>' +",
    "'<div class=\"value\">' + escapeHtml(h['内容メモ']) + '</div></div>';",
    "}).join('');",
    "}",

    "function renderMemoField(memoValue){",
    "return '<div class=\"field\" id=\"memoField\"><div class=\"label\">関係メモ' +",
    "'<button class=\"btn-small\" id=\"memoEditBtn\" type=\"button\">編集</button></div>' +",
    "'<div class=\"value\" id=\"memoValue\">' + (escapeHtml(memoValue) || '—') + '</div>' +",
    "'<textarea id=\"memoTextarea\" style=\"display:none\"></textarea>' +",
    "'<div id=\"memoEditControls\" style=\"display:none\">' +",
    "'<button class=\"btn-small btn-primary\" id=\"memoSaveBtn\" type=\"button\">保存</button>' +",
    "'<button class=\"btn-small\" id=\"memoCancelBtn\" type=\"button\">キャンセル</button>' +",
    "'<span id=\"memoStatus\"></span></div></div>';",
    "}",

    "function attachMemoHandlers(companyId, originalMemo){",
    "memoEditing = false; memoCompanyId = companyId; memoOriginalValue = originalMemo || '';",
    "document.getElementById('memoEditBtn').addEventListener('click', startMemoEdit);",
    "document.getElementById('memoSaveBtn').addEventListener('click', saveMemo);",
    "document.getElementById('memoCancelBtn').addEventListener('click', cancelMemoEdit);",
    "}",

    "function startMemoEdit(){",
    "memoEditing = true;",
    "document.getElementById('memoValue').style.display = 'none';",
    "var ta = document.getElementById('memoTextarea');",
    "ta.value = memoOriginalValue; ta.style.display = 'block';",
    "document.getElementById('memoEditControls').style.display = 'flex';",
    "document.getElementById('memoStatus').className = ''; document.getElementById('memoStatus').textContent = '';",
    "}",

    "function cancelMemoEdit(){",
    "memoEditing = false;",
    "document.getElementById('memoTextarea').style.display = 'none';",
    "document.getElementById('memoEditControls').style.display = 'none';",
    "document.getElementById('memoValue').style.display = 'block';",
    "document.getElementById('memoStatus').className = ''; document.getElementById('memoStatus').textContent = '';",
    "}",

    "function saveMemo(){",
    "var savingCompanyId = memoCompanyId;",
    "var newValue = document.getElementById('memoTextarea').value;",
    "document.getElementById('memoSaveBtn').disabled = true;",
    "document.getElementById('memoCancelBtn').disabled = true;",
    "document.getElementById('memoStatus').className = '';",
    "document.getElementById('memoStatus').textContent = '保存中...';",
    "google.script.run.withSuccessHandler(function(){",
    "if (memoCompanyId !== savingCompanyId) { return; }",
    "memoOriginalValue = newValue; memoEditing = false;",
    "document.getElementById('memoValue').textContent = newValue || '—';",
    "document.getElementById('memoTextarea').style.display = 'none';",
    "document.getElementById('memoEditControls').style.display = 'none';",
    "document.getElementById('memoValue').style.display = 'block';",
    "document.getElementById('memoSaveBtn').disabled = false;",
    "document.getElementById('memoCancelBtn').disabled = false;",
    "document.getElementById('memoStatus').textContent = '保存しました';",
    "}).withFailureHandler(function(){",
    "if (memoCompanyId !== savingCompanyId) { return; }",
    "document.getElementById('memoSaveBtn').disabled = false;",
    "document.getElementById('memoCancelBtn').disabled = false;",
    "document.getElementById('memoStatus').className = 'error';",
    "document.getElementById('memoStatus').textContent = '保存に失敗しました。もう一度お試しください。';",
    "}).updateCompanyMemo(memoCompanyId, newValue);",
    "}",

    "function closeDrawer(){",
    "if (memoEditing && !confirm('保存されていない変更があります。破棄しますか?')) { return; }",
    "memoEditing = false;",
    "document.getElementById('drawer').classList.remove('open');",
    "document.getElementById('overlay').classList.remove('open');",
    "}",

    "var shareTargetCompanyId = null;",
    "var shareTargetCompanyName = null;",
    "var shareTargetDnc = false;",

    "function openShareModal(){",
    "shareTargetCompanyId = document.getElementById('drawerCompanyId').textContent;",
    "shareTargetCompanyName = document.getElementById('drawerCompanyName').textContent;",
    "document.getElementById('shareTitle').textContent = shareTargetCompanyName + ' を連携';",
    "document.getElementById('shareDncWarn').style.display = shareTargetDnc ? 'block' : 'none';",
    "document.getElementById('shareStatus').textContent = '';",
    "google.script.run.withSuccessHandler(function(staffList){",
    "document.getElementById('shareStaffList').innerHTML = staffList.map(function(s){",
    "return '<label><input type=\"checkbox\" value=\"'+escapeHtml(s.slackUserId)+'\"> '+escapeHtml(s.name)+'</label>';",
    "}).join('');",
    "document.getElementById('shareNote').value = '';",
    "updateSharePreview();",
    "document.querySelectorAll('#shareStaffList input').forEach(function(el){",
    "el.addEventListener('change', updateSharePreview);",
    "});",
    "}).withFailureHandler(function(){",
    "document.getElementById('shareStaffList').innerHTML = '<p class=\"empty-note\">スタッフ一覧の読み込みに失敗しました。</p>';",
    "}).getShareableStaffList();",
    "document.getElementById('shareModal').classList.add('open');",
    "document.getElementById('overlay').classList.add('open');",
    "}",

    "function updateSharePreview(){",
    "var checked = Array.prototype.slice.call(document.querySelectorAll('#shareStaffList input:checked')).map(function(el){ return el.value; });",
    "var note = document.getElementById('shareNote').value;",
    "document.getElementById('sharePreview').textContent = shareTargetCompanyName + ' の情報を連携します。宛先: ' + checked.length + '名' + (note ? ' / メモ: ' + note : '');",
    "}",

    "function closeShareModal(){",
    "document.getElementById('shareModal').classList.remove('open');",
    "document.getElementById('overlay').classList.remove('open');",
    "}",

    "function sendShare(){",
    "var checked = Array.prototype.slice.call(document.querySelectorAll('#shareStaffList input:checked')).map(function(el){ return el.value; });",
    "if (checked.length===0){ document.getElementById('shareStatus').textContent = '連携先を選択してください。'; return; }",
    "var note = document.getElementById('shareNote').value;",
    "document.getElementById('shareSendBtn').disabled = true;",
    "document.getElementById('shareStatus').textContent = '送信中...';",
    "google.script.run.withSuccessHandler(function(resultText){",
    "document.getElementById('shareSendBtn').disabled = false;",
    "document.getElementById('shareStatus').textContent = resultText;",
    "}).withFailureHandler(function(){",
    "document.getElementById('shareSendBtn').disabled = false;",
    "document.getElementById('shareStatus').textContent = '連携に失敗しました。もう一度お試しください。';",
    "}).shareCompanyWithStaff(shareTargetCompanyId, checked, note);",
    "}",

    "function openLetterPreview(){",
    "var companyId = document.getElementById('drawerCompanyId').textContent;",
    "document.getElementById('letterPreviewBody').innerHTML = '<p class=\"empty-note\">読み込み中…</p>';",
    "document.getElementById('letterPreviewModal').classList.add('open');",
    "document.getElementById('overlay').classList.add('open');",
    "google.script.run.withSuccessHandler(function(draft){",
    "if (!draft){ document.getElementById('letterPreviewBody').innerHTML = '<p class=\"empty-note\">下書きなし</p>'; return; }",
    "document.getElementById('letterPreviewBody').innerHTML =",
    "'<div class=\"field\"><div class=\"label\">生成日時</div><div class=\"value\">'+escapeHtml(draft['生成日時'])+'</div></div>' +",
    "'<div class=\"field\"><div class=\"label\">ステータス</div><div class=\"value\">'+escapeHtml(draft['ステータス'])+'</div></div>' +",
    "'<div class=\"field\"><div class=\"label\">本文</div><div class=\"value\">'+escapeHtml(draft['本文'])+'</div></div>';",
    "}).withFailureHandler(function(){",
    "document.getElementById('letterPreviewBody').innerHTML = '<p class=\"empty-note\">読み込みに失敗しました。</p>';",
    "}).getLatestLetterDraft(companyId);",
    "}",

    "function closeLetterPreview(){",
    "document.getElementById('letterPreviewModal').classList.remove('open');",
    "document.getElementById('overlay').classList.remove('open');",
    "}",

    "function switchView(target){",
    "var isCompany = target === 'company';",
    "document.getElementById('viewCompanyBtn').classList.toggle('active', isCompany);",
    "document.getElementById('viewPartnerBtn').classList.toggle('active', !isCompany);",
    "document.getElementById('companyView').classList.toggle('active', isCompany);",
    "document.getElementById('partnerView').classList.toggle('active', !isCompany);",
    "document.getElementById('companyFiltersBar').style.display = isCompany ? 'flex' : 'none';",
    "}",

    "function loadPartnerList(){",
    "google.script.run.withSuccessHandler(renderPartnerTable).withFailureHandler(function(error){",
    "document.getElementById('partnerTableBody').innerHTML = '';",
    "var empty = document.getElementById('partnerEmptyState');",
    "empty.style.display = 'block'; empty.textContent = '読み込みに失敗しました。再読み込みしてください。';",
    "}).getPartnerList();",
    "}",

    "function renderPartnerTable(rows){",
    "var tbody = document.getElementById('partnerTableBody'); tbody.innerHTML = '';",
    "var empty = document.getElementById('partnerEmptyState');",
    "if (!rows || rows.length === 0){ empty.style.display = 'block';",
    "empty.textContent = '該当するパートナーが見つかりません'; return; }",
    "empty.style.display = 'none';",
    "rows.forEach(function(row){",
    "var tr = document.createElement('tr');",
    "tr.innerHTML = '<td>' + escapeHtml(row['名称']) + '</td>' +",
    "'<td>' + escapeHtml(row['種別']) + '</td>' +",
    "'<td>' + escapeHtml(row['関係性ランク']) + '</td>' +",
    "'<td>' + escapeHtml(row['対応回数']) + '</td>';",
    "tr.addEventListener('click', function(){ openPartnerDrawer(row['パートナーID']); });",
    "tbody.appendChild(tr);});",
    "}",

    "function openPartnerDrawer(partnerId){",
    "document.getElementById('partnerDrawer').classList.add('open');",
    "document.getElementById('partnerOverlay').classList.add('open');",
    "document.getElementById('partnerDrawerName').textContent = '読み込み中…';",
    "document.getElementById('partnerDrawerId').textContent = partnerId;",
    "google.script.run.withSuccessHandler(renderPartnerDrawer).withFailureHandler(function(){",
    "document.getElementById('partnerDrawerName').textContent = '読み込みに失敗しました。再読み込みしてください。';",
    "}).getPartnerDetail(partnerId);",
    "}",

    "function renderPartnerDrawer(detail){",
    "if (!detail){ document.getElementById('partnerDrawerName').textContent = '該当するパートナーが見つかりません';",
    "document.getElementById('panePartnerOverview').innerHTML = '';",
    "document.getElementById('panePartnerHistory').innerHTML = '';",
    "document.getElementById('panePartnerReferrals').innerHTML = ''; return; }",
    "var p = detail.partner;",
    "document.getElementById('partnerDrawerName').textContent = p['名称'] || '(名称未登録)';",
    "document.getElementById('partnerDrawerId').textContent = p['パートナーID'];",
    "var fields = [",
    "['種別', p['種別']], ['担当者名', p['担当者名']], ['関係性ランク', p['関係性ランク']],",
    "['累計紹介数', p['累計紹介数']], ['成約数', p['成約数']],",
    "['提供済み情報ログ', p['提供済み情報ログ']], ['逆紹介履歴', p['逆紹介履歴']]",
    "];",
    "document.getElementById('panePartnerOverview').innerHTML = fields.map(function(f){",
    "return '<div class=\"field\"><div class=\"label\">' + escapeHtml(f[0]) + '</div>' +",
    "'<div class=\"value\">' + (escapeHtml(f[1]) || '—') + '</div></div>';",
    "}).join('');",
    "var history = detail.history || [];",
    "document.getElementById('panePartnerHistory').innerHTML = history.length === 0",
    "? '<div class=\"empty\">対応履歴がありません</div>'",
    ": history.map(function(h){",
    "return '<div class=\"field\"><div class=\"label\">' + escapeHtml(h['日付']) + '</div>' +",
    "'<div class=\"value\">' + escapeHtml(h['内容メモ']) + '</div></div>';",
    "}).join('');",
    "var referrals = detail.referrals || [];",
    "document.getElementById('panePartnerReferrals').innerHTML = referrals.length === 0",
    "? '<div class=\"empty\">紹介実績がありません</div>'",
    ": referrals.map(function(r){",
    "return '<div class=\"field\"><div class=\"label\">' + escapeHtml(r['紹介日']) + '・紹介料率: ' + escapeHtml(r['紹介料率']) + '</div>' +",
    "'<div class=\"value\">' + escapeHtml(r['契約内容メモ']) + '(成約有無: ' + escapeHtml(r['成約有無']) + ')</div></div>';",
    "}).join('');",
    "}",

    "function closePartnerDrawer(){",
    "document.getElementById('partnerDrawer').classList.remove('open');",
    "document.getElementById('partnerOverlay').classList.remove('open');",
    "}",

    "function switchTab(target){",
    "var isOverview = target === 'overview';",
    "document.getElementById('tabOverviewBtn').classList.toggle('active', isOverview);",
    "document.getElementById('tabHistoryBtn').classList.toggle('active', !isOverview);",
    "document.getElementById('paneOverview').style.display = isOverview ? 'block' : 'none';",
    "document.getElementById('paneHistory').style.display = isOverview ? 'none' : 'block';",
    "}",

    "function switchPartnerTab(target){",
    "var isOverview = target === 'overview';",
    "var isHistory = target === 'history';",
    "document.getElementById('tabPartnerOverviewBtn').classList.toggle('active', isOverview);",
    "document.getElementById('tabPartnerHistoryBtn').classList.toggle('active', isHistory);",
    "document.getElementById('tabPartnerReferralsBtn').classList.toggle('active', !isOverview && !isHistory);",
    "document.getElementById('panePartnerOverview').style.display = isOverview ? 'block' : 'none';",
    "document.getElementById('panePartnerHistory').style.display = isHistory ? 'block' : 'none';",
    "document.getElementById('panePartnerReferrals').style.display = (!isOverview && !isHistory) ? 'block' : 'none';",
    "}",

    "document.getElementById('searchInput').addEventListener('input', function(e){",
    "currentFilters.search = e.target.value; loadList(); });",
    "document.getElementById('filterRank').addEventListener('change', function(e){",
    "currentFilters.rank = e.target.value; loadList(); });",
    "document.getElementById('filterStage').addEventListener('change', function(e){",
    "currentFilters.stage = e.target.value; loadList(); });",
    "document.getElementById('filterOwner').addEventListener('change', function(e){",
    "currentFilters.owner = e.target.value; loadList(); });",
    "document.getElementById('filterRoute').addEventListener('change', function(e){",
    "currentFilters.route = e.target.value; loadList(); });",
    "document.getElementById('filterProduct').addEventListener('change', function(e){",
    "currentFilters.product = e.target.value; loadList(); });",
    "document.getElementById('drawerClose').addEventListener('click', closeDrawer);",
    "document.getElementById('overlay').addEventListener('click', closeDrawer);",
    "document.getElementById('tabOverviewBtn').addEventListener('click', function(){ switchTab('overview'); });",
    "document.getElementById('tabHistoryBtn').addEventListener('click', function(){ switchTab('history'); });",
    "document.getElementById('viewCompanyBtn').addEventListener('click', function(){ switchView('company'); });",
    "document.getElementById('viewPartnerBtn').addEventListener('click', function(){ switchView('partner'); });",
    "document.getElementById('partnerDrawerClose').addEventListener('click', closePartnerDrawer);",
    "document.getElementById('partnerOverlay').addEventListener('click', closePartnerDrawer);",
    "document.getElementById('tabPartnerOverviewBtn').addEventListener('click', function(){ switchPartnerTab('overview'); });",
    "document.getElementById('tabPartnerHistoryBtn').addEventListener('click', function(){ switchPartnerTab('history'); });",
    "document.getElementById('tabPartnerReferralsBtn').addEventListener('click', function(){ switchPartnerTab('referrals'); });",
    "document.getElementById('kpiModalClose').addEventListener('click', closeKpiModal);",
    "document.getElementById('kpiScrim').addEventListener('click', closeKpiModal);",
    "document.getElementById('shareBtn').addEventListener('click', openShareModal);",
    "document.getElementById('shareModalClose').addEventListener('click', closeShareModal);",
    "document.getElementById('shareSendBtn').addEventListener('click', sendShare);",
    "document.getElementById('shareNote').addEventListener('input', updateSharePreview);",
    "document.getElementById('letterPreviewBtn').addEventListener('click', openLetterPreview);",
    "document.getElementById('letterPreviewModalClose').addEventListener('click', closeLetterPreview);",

    "loadFilterOptions();",
    "loadKpiSummary();",
    "loadQueue();",
    "loadWorkload();",
    "loadList();",
    "loadPartnerList();"
  ].join("");

  function buildAdminAppHtml() {
    return "<!doctype html><html lang=\"ja\"><head><meta charset=\"utf-8\">" +
      "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">" +
      "<style>" + STYLE + "</style></head><body>" +
      "<div class=\"app\">" +
      HEADER_AND_FILTERS +
      "<div class=\"body-grid\">" + KPI_ROW + TABLE + SIDE_PANEL + PARTNER_VIEW + "</div>" +
      "</div>" +
      DRAWER + PARTNER_DRAWER + KPI_MODAL + SHARE_MODAL + LETTER_PREVIEW_MODAL +
      "<script>" + SCRIPT + "<\/script>" +
      "</body></html>";
  }

  var api = {
    buildAdminAppHtml: buildAdminAppHtml
  };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = api;
  } else {
    global.GlowAdminApp = api;
  }
})(typeof window !== "undefined" ? window : globalThis);
